const NS='http://www.w3.org/2000/svg',$=s=>document.querySelector(s);
const worlds=[
 {id:'earth-616',name:'Earth-616',color:'#7ef0bd',subtitle:'Główna rzeczywistość · 1943–2025'},
 {id:'earth-838',name:'Earth-838',color:'#a98aff',subtitle:'Świat Illuminati · odgałęzienie 2018',parent:'earth-616'},
 {id:'zombie',name:'Marvel Zombies',color:'#ff7272',subtitle:'Świat zakażenia · odgałęzienie 2023',parent:'earth-616'}
];
const people={
 steve:{name:'Steve Rogers',hero:'Kapitan Ameryka',color:'#68b7ff',tags:['Steve Rogers','Kapitan Ameryka','Avengers'],points:[[390,758],[620,665],[360,548],[380,388],[620,260],[650,146]]},
 tony:{name:'Tony Stark',hero:'Iron Man',color:'#ff6f61',tags:['Tony Stark','Iron Man','Avengers'],points:[[380,548],[620,435],[390,315],[620,260]]},
 thor:{name:'Thor Odinson',hero:'Thor',color:'#efc46c',tags:['Thor Odinson','Thor','Avengers'],points:[[1160,650],[380,548],[1160,450],[620,260],[690,146]]},
 wanda:{name:'Wanda Maximoff',hero:'Scarlet Witch',color:'#df78c8',tags:['Wanda Maximoff','Scarlet Witch','Avengers'],points:[[650,450],[620,260],[650,196],[1100,146]]},
 claire:{name:'Claire Voyant',hero:'Black Widow',color:'#b58cff',tags:['Claire Voyant','Black Widow','Golden Age'],points:[[380,758],[1290,720],[390,675]]}
};
const mainEvents=[
 {title:'Narodziny Kapitana Ameryki',year:'1943',x:390,y:758,char:'steve',place:'Nowy Jork · Ameryka',source:'The First Avenger',tags:['Steve Rogers','Kapitan Ameryka','Origin']},
 {title:'Black Widow wraca z Piekła',year:'1944',x:390,y:675,char:'claire',place:'Ziemia / Piekło',source:'Mystic Comics #4',tags:['Claire Voyant','Black Widow','Golden Age'],copy:'Piekło jest regionem metafizycznym należącym do tego świata — nie osobnym uniwersum.'},
 {title:'Bitwa o Nowy Jork',year:'2012',x:380,y:548,char:'steve',place:'Nowy Jork · Ameryka',source:'The Avengers',tags:['Avengers','Steve Rogers','Tony Stark','Thor'],copy:'Węzeł spotkania: linie uczestników schodzą się w jednym wydarzeniu.'},
 {title:'Ultron pokonany',year:'2015',x:620,y:435,char:'tony',place:'Sokovia · Europa',source:'Age of Ultron',tags:['Avengers','Tony Stark','Wanda Maximoff']},
 {title:'Blip',year:'2018',x:390,y:315,char:'tony',place:'Wakanda · Afryka',source:'Infinity War',tags:['Avengers','Infinity War','World Shift']},
 {title:'Ostateczna bitwa',year:'2023',x:620,y:260,char:'steve',place:'Avengers Compound · Ameryka',source:'Endgame',tags:['Avengers','Endgame','Tony Stark','Steve Rogers'],copy:'Globalne wydarzenie; półprzezroczysta płaszczyzna pokazuje nowy stan świata.'},
 {title:'Przejście do Earth-838',year:'2025',x:1100,y:146,char:'wanda',place:'Kamar-Taj → Earth-838',source:'Multiverse of Madness',tags:['Wanda Maximoff','Scarlet Witch','Multiverse'],target:'earth-838',copy:'Kolorowy odcinek oznacza pobyt w innym świecie. Kliknięcie otwiera jego historię.'}
];
const otherEvents={
 'earth-838':[{title:'Illuminati strzegą świata',year:'2018',x:620,y:315,place:'Nowy Jork · Earth-838',source:'Multiverse of Madness',tags:['Illuminati','Earth-838']},{title:'Wanda przybywa z Earth-616',year:'2025',x:620,y:146,place:'Siedziba Illuminati',source:'Multiverse of Madness',tags:['Wanda Maximoff','Multiverse'],target:'earth-616'}],
 zombie:[{title:'Początek zakażenia',year:'2023',x:620,y:260,place:'Nowy Jork',source:'Marvel Zombies',tags:['Zombies','World Shift']},{title:'Upadek bohaterów',year:'2024',x:390,y:205,place:'Ameryka',source:'Marvel Zombies',tags:['Zombies','Avengers']}]
};
let active='earth-616',tag='',query='',zoom=1;
const svg=$('#story-map');
const el=(name,attrs={},text='')=>{const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;return n};
const line=pts=>pts.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ');
function append(parent,...nodes){nodes.forEach(n=>parent.append(n));}

function tabs(){const nav=$('#world-tabs');nav.innerHTML='';worlds.forEach(w=>{const b=document.createElement('button');b.className='world-tab'+(w.id===active?' active':'');b.innerHTML='<i style="background:'+w.color+'"></i>'+w.name;b.onclick=()=>switchWorld(w.id);nav.append(b)});const b=document.createElement('button');b.className='world-tab world-more';b.textContent='Wszystkie światy ▾';nav.append(b)}
function switchWorld(id){active=id;tag='';query='';$('#search').value='';const w=worlds.find(x=>x.id===id);$('#world-title').textContent=w.name;$('#world-subtitle').textContent=w.subtitle;tabs();tags();render();show({title:w.name,copy:w.parent?'Świat potomny dziedziczy historię do punktu rozgałęzienia.':'Główne drzewo aktywnej rzeczywistości.',place:w.subtitle,tags:[w.name]},'ŚWIAT')}
function matches(item){const hay=[item.title,item.name,item.hero,item.place,...(item.tags||[])].filter(Boolean).join(' ').toLowerCase();return(!tag||(item.tags||[]).includes(tag))&&(!query||hay.includes(query.toLowerCase()))}

function base(g){
 const defs=el('defs'),marker=el('marker',{id:'arrow-muted',viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});marker.append(el('path',{d:'M0 0L10 5L0 10z',fill:'var(--muted)'}));defs.append(marker);g.append(defs);
 [[1943,758],[1945,675],[2012,548],[2015,435],[2018,315],[2023,260],[2025,146]].forEach(([year,y])=>append(g,el('line',{x1:82,y1:y,x2:1360,y2:y,class:'time-line'}),el('text',{x:28,y:y+4,class:'map-year'},year)));
 g.append(el('text',{x:24,y:92,class:'location-label'},'CZAS ↑'));
 const realm=el('g');append(realm,el('rect',{x:1110,y:610,width:270,height:205,rx:30,class:'realm-plane'}),el('text',{x:1140,y:645,class:'location-label'},'POZA ZIEMIĄ · '+active.toUpperCase()),el('text',{x:1140,y:680,class:'map-note'},'KOSMOS'),el('text',{x:1260,y:775,class:'map-note'},'PIEKŁO'));g.append(realm);
 const p=el('g');append(p,el('ellipse',{cx:610,cy:760,rx:485,ry:110,class:'earth-plane'}),el('path',{d:'M210 738c30-49 99-70 153-48 33 13 39 44 15 65-20 18-9 50-50 65-38 13-69-11-76-39-7-29-59-7-42-43z',class:'continent'}),el('path',{d:'M510 692c54-31 144-35 206-11 40 16 85 8 121 34 29 21 17 45-17 53-46 11-72-15-110-2-32 11-21 57-68 61-50 5-68-46-104-56-48-12-73-53-28-79z',class:'continent'}),el('path',{d:'M832 711c58-25 144-18 180 15 26 24 7 57-39 60-58 4-117 11-150-25-17-18-12-39 9-50z',class:'continent'}),el('text',{x:260,y:855,class:'location-label'},'AMERYKA'),el('text',{x:592,y:855,class:'location-label'},'EUROPA / AFRYKA'),el('text',{x:900,y:855,class:'location-label'},'AZJA'));g.append(p);
 if(active==='earth-616'){const s=el('g');append(s,el('ellipse',{cx:610,cy:260,rx:420,ry:78,class:'shift-plane'}),el('text',{x:805,y:245,class:'shift-title'},'WORLD SHIFT · 2023'),el('text',{x:805,y:262,class:'map-note'},'nowa wersja mapy od tego momentu'));s.onclick=()=>show({title:'World Shift: świat po Blipie',year:'2023',place:'Earth-616',source:'Avengers: Endgame',tags:['World Shift','Mapa v2'],copy:'Nowa półprzezroczysta płaszczyzna mapy. Stary stan świata pozostaje widoczny poniżej.'},'WORLD SHIFT');g.append(s)}
}
function main(g){
 Object.values(people).forEach(c=>{const d=line(c.points);append(g,el('path',{d,class:'thread '+(matches(c)?'focused':'muted'),stroke:c.color}),(()=>{const n=el('path',{d,class:'thread-hit'});n.onclick=()=>show({title:c.name,copy:c.hero+' · ścieżka postaci przez miejsca i wydarzenia.',tags:c.tags,place:'Kliknij hashtag, aby odfiltrować drzewo.'},'POSTAĆ');return n})());const [x,y]=c.points.at(-1);g.append(el('text',{x:x+10,y:y-9,class:'person-label',fill:c.color},c.name))});
 const travel=el('path',{d:'M650 196C790 175 930 168 1100 146',class:'travel-segment',stroke:'#a98aff'});travel.onclick=()=>switchWorld('earth-838');g.append(travel);
 const mention=el('path',{d:'M930 388C830 430 760 505 705 548',class:'mentioned-line'});mention.onclick=()=>show({title:'Tajne spotkanie',year:'2012',place:'Europa',source:'Wspomniane w 2017',tags:['Mentioned','Retrospekcja'],copy:'Cienka linia cofa się od momentu ujawnienia do czasu rzeczywistego wydarzenia.'},'WYDARZENIE WSPOMNIANE');g.append(mention);
 mainEvents.forEach(e=>event(g,e));const b=el('g',{class:'branch-node'});append(b,el('polygon',{points:'610,307 620,297 630,307 620,317'}),el('text',{x:638,y:311},'odgałęzienie: Marvel Zombies'));b.onclick=()=>switchWorld('zombie');g.append(b)
}
function other(g){const w=worlds.find(x=>x.id===active),x=active==='earth-838'?620:390;g.append(el('path',{d:`M${x} 760C${x-30} 600 ${x+40} 410 ${x} 146`,class:'thread focused',stroke:w.color}));otherEvents[active].forEach(e=>event(g,e));const b=el('g',{class:'branch-node'});append(b,el('polygon',{points:'110,112 120,102 130,112 120,122'}),el('text',{x:140,y:116},'powrót do Earth-616'));b.onclick=()=>switchWorld('earth-616');g.append(b)}
function event(g,e){const color=e.char?people[e.char].color:worlds.find(w=>w.id===active).color,n=el('g',{class:'event-node event-group '+(matches(e)?'':'muted'),style:'color:'+color});append(n,el('circle',{cx:e.x,cy:e.y,r:7}),el('text',{x:e.x+13,y:e.y-9},e.title));n.onclick=()=>show(e,e.target?'PRZEJŚCIE MIĘDZY ŚWIATAMI':'WYDARZENIE');g.append(n)}
function render(){svg.innerHTML='';const g=el('g',{transform:`translate(${720-720*zoom} ${450-450*zoom}) scale(${zoom})`});svg.append(g);base(g);active==='earth-616'?main(g):other(g)}
function tags(){const items=active==='earth-616'?Object.values(people):otherEvents[active],all=[...new Set(items.flatMap(x=>x.tags||[]))];const box=$('#tag-filters');box.innerHTML='';all.slice(0,9).forEach(t=>{const b=document.createElement('button');b.className='tag-chip'+(tag===t?' active':'');b.textContent='#'+t.replaceAll(' ','');b.onclick=()=>{tag=tag===t?'':t;tags();render();$('#btn-clear-filter').hidden=!tag&&!query};box.append(b)})}
function show(item,kicker='WYDARZENIE'){$('#inspector-kicker').textContent=kicker;$('#inspector-title').textContent=item.title||item.name;$('#inspector-copy').textContent=item.copy||'Element aktualnie oglądanej historii.';$('#inspector-meta').innerHTML=[['Czas',item.year],['Miejsce',item.place],['Źródło',item.source]].filter(x=>x[1]).map(([a,b])=>'<dt>'+a+'</dt><dd>'+b+'</dd>').join('');$('#inspector-tags').innerHTML=(item.tags||[]).map(t=>'<span>#'+t.replaceAll(' ','')+'</span>').join('');const a=$('#inspector-action');if(item.target){const w=worlds.find(x=>x.id===item.target);a.hidden=false;a.textContent='Przejdź do '+w.name;a.onclick=()=>switchWorld(w.id)}else a.hidden=true}
$('#search').oninput=e=>{query=e.target.value.trim();$('#btn-clear-filter').hidden=!query&&!tag;render()};$('#btn-clear-filter').onclick=()=>{query='';tag='';$('#search').value='';tags();render();$('#btn-clear-filter').hidden=true};$('#btn-theme').onclick=()=>document.body.classList.toggle('light');$('#btn-add').onclick=()=>$('#add-dialog').showModal();$('#btn-fit').onclick=()=>{zoom=1;render()};$('#zoom-in').onclick=()=>{zoom=Math.min(1.6,zoom+.15);render()};$('#zoom-out').onclick=()=>{zoom=Math.max(.65,zoom-.15);render()};$('#btn-play').onclick=()=>[...svg.querySelectorAll('.event-node circle')].forEach((n,i)=>setTimeout(()=>n.animate([{r:7},{r:15},{r:7}],{duration:650}),i*350));$('#inspector-close').onclick=()=>$('#inspector').classList.toggle('hidden');$('#btn-help').onclick=()=>show({title:'Jak czytać Chronizo?',copy:'Czas rośnie ku górze. Położenie linii odpowiada miejscu. Kolorowy romb otwiera inny świat. Obszary obok mapy należą do aktywnej rzeczywistości.',tags:['Mapa','Czas','Światy']},'POMOC');
document.querySelectorAll('.rail-button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rail-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view!=='world')show({title:b.textContent.trim(),copy:'Ten widok wykorzysta ten sam model danych. W pierwszym prototypie dopracowujemy mapę świata.',tags:['Prototyp']},'WIDOK W PRZYGOTOWANIU')});
tabs();tags();render();show({title:'Earth-616',copy:'Główne drzewo aktywnej rzeczywistości.',place:worlds[0].subtitle,tags:['Earth-616']},'ŚWIAT');
