const STORAGE_KEY='chronizo.workbench.v1';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const freshState=()=>({projects:[],activeProjectId:null});
let state=load();
let selectedRelationId=null;
let roadMode='sources';
let editingSourceId=null;
let editingEventId=null;
let editingCharacterId=null;
const RELATION_TYPES=new Set(['before','after','parallel']);

function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return parsed&&Array.isArray(parsed.projects)?parsed:freshState()}catch{return freshState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function activeProject(){return state.projects.find(project=>project.id===state.activeProjectId)||null}
function projectWorlds(){const project=activeProject();if(!project)return[];return project.worlds||(project.worlds=[])}
function worldLabel(world){return world.number?`Earth-${world.number}`:world.name||'Świat bez numeru'}
function projectCharacters(){const project=activeProject();if(!project)return[];return project.characters||(project.characters=[])}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function openDialog(selector){const dialog=$(selector);dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type="checkbox"]),textarea,select')?.focus())}
function empty(icon,title,copy,action='',buttonId=''){return `<div class="empty-state"><div class="empty-state-inner"><div class="empty-icon">${icon}</div><h2>${title}</h2><p>${copy}</p>${action?`<button id="${buttonId}" class="primary-button" type="button">${action}</button>`:''}</div></div>`}

function renderProjectSelect(){const select=$('#project-select');select.innerHTML='';if(!state.projects.length){const option=document.createElement('option');option.textContent='Brak projektu';option.value='';select.append(option);select.disabled=true;return}select.disabled=false;state.projects.forEach(project=>{const option=document.createElement('option');option.value=project.id;option.textContent=project.name;option.selected=project.id===state.activeProjectId;select.append(option)})}
function dateLabel(value,approx=false){if(!value)return 'data nieustalona';return (approx?'około ':'')+escapeHtml(value)}
function itemActions(type,id){return `<div class="item-actions"><button class="edit-${type}" data-id="${id}" type="button" title="Edytuj">✎</button><button class="delete-${type}" data-id="${id}" type="button" title="Usuń">×</button></div>`}
function sourceRow(source){return `<article class="list-item"><span class="list-mark">▤</span><div class="list-copy"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)} · ${dateLabel(source.date,source.dateApprox)}</small></div><span class="status">${escapeHtml(source.status)}</span>${itemActions('source',source.id)}</article>`}
function eventSourceIds(event){return [...new Set([event.sourceId,...(event.sourceIds||[])].filter(Boolean))]}
function eventSources(event){const ids=eventSourceIds(event);return (activeProject()?.sources||[]).filter(source=>ids.includes(source.id))}
function eventChronologyDate(event){const inherited=eventSources(event).map(source=>source.date).filter(Boolean).sort()[0];return event.date||inherited||'9999-12-31'}
function orderEventsChronologically(events){const ordered=events.slice().sort((a,b)=>eventChronologyDate(a).localeCompare(eventChronologyDate(b))||a.createdAt.localeCompare(b.createdAt));for(let pass=0;pass<ordered.length*2;pass++){let changed=false;for(const event of [...ordered]){if(!RELATION_TYPES.has(event.timeType)||!event.relationEventId)continue;const from=ordered.indexOf(event),target=ordered.findIndex(item=>item.id===event.relationEventId);if(target<0)continue;const wantsBefore=event.timeType==='before',wrong=wantsBefore?from>target:event.timeType==='after'?from<target:Math.abs(from-target)>1;if(!wrong)continue;ordered.splice(from,1);const nextTarget=ordered.findIndex(item=>item.id===event.relationEventId);ordered.splice(wantsBefore?nextTarget:nextTarget+1,0,event);changed=true}if(!changed)break}return ordered}
function renderRoad(){
 const project=activeProject(),content=$('#road-content'),button=$('#new-project-main');
 if(!project){$('#road-title').textContent='Zacznij własną kronikę';$('#road-subtitle').textContent='Bez przykładów. Bez narzuconego uniwersum. To miejsce czeka na Twoją historię.';button.textContent='Utwórz pierwszy projekt';content.innerHTML=empty('◫','Tabula rasa','Utwórz projekt, nadaj mu własną nazwę i zacznij dodawać materiały. Chronizo nie wstawia żadnych przykładowych światów, postaci ani wydarzeń.','Utwórz projekt','empty-new-project');$('#empty-new-project').onclick=()=>openDialog('#project-dialog');return}
 const sources=project.sources||[],events=project.events||[],inbox=events.filter(event=>event.inbox),orderedSources=sources.slice().sort((a,b)=>(a.date||'9999-12-31').localeCompare(b.date||'9999-12-31')||a.createdAt.localeCompare(b.createdAt)),orderedEvents=orderEventsChronologically(events),roadItems=roadMode==='events'?orderedEvents:orderedSources;
 $('#road-title').textContent=project.name;$('#road-subtitle').textContent=project.description||'Twoja droga przez źródła i wydarzenia.';button.textContent='＋ Dodaj źródło';
 content.innerHTML=`<div class="road-modes" role="tablist" aria-label="Sposób budowania drogi"><button class="${roadMode==='sources'?'active':''}" data-road-mode="sources" type="button">▤ Według źródeł</button><button class="${roadMode==='events'?'active':''}" data-road-mode="events" type="button">● Chronologia wydarzeń</button></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h2>${roadMode==='events'?'Chronologia wydarzeń':'Kolejność źródeł'}</h2><span class="counter">${roadItems.length}</span></div>${roadItems.length?`<div class="list">${roadItems.map(roadMode==='events'?eventRow:sourceRow).join('')}</div>`:empty(roadMode==='events'?'●':'▤',roadMode==='events'?'Brak wydarzeń':'Droga jest jeszcze pusta',roadMode==='events'?'Dodaj pierwsze wydarzenie, aby zacząć budować chronologię.':'Dodaj pierwszy film, serial, komiks albo inne źródło.',roadMode==='events'?'Dodaj wydarzenie':'Dodaj źródło','road-add-item')}</div><div><div class="panel"><div class="panel-head"><h2>Stan kroniki</h2></div><div class="metric-grid"><div class="metric"><strong>${sources.length}</strong><span>źródła</span></div><div class="metric"><strong>${events.length}</strong><span>wydarzenia</span></div><div class="metric"><strong>${inbox.length}</strong><span>do uporządkowania</span></div></div></div></div></div>`;
 const worlds=projectWorlds(),side=content.querySelector('.dashboard-grid>div:last-child');side.insertAdjacentHTML('beforeend',`<div class="panel worlds-panel"><div class="panel-head"><h2>Światy projektu</h2><button id="add-world-button" class="mini-button" type="button">＋</button></div>${worlds.length?`<div class="world-chip-list">${worlds.map(world=>`<span><b>${escapeHtml(worldLabel(world))}</b>${world.description?`<small>${escapeHtml(world.description)}</small>`:''}</span>`).join('')}</div>`:'<p class="panel-note">Dodaj światy, aby przypisywać do nich wydarzenia i budować spotkania.</p>'}</div>`);
 $$('.road-modes button').forEach(mode=>mode.addEventListener('click',()=>{roadMode=mode.dataset.roadMode;renderRoad()}));
 $('#road-add-item')?.addEventListener('click',roadMode==='events'?openEventDialog:openSourceDialog);
 $('#add-world-button')?.addEventListener('click',openWorldDialog);
}
function bindProjectEmpty(id){$('#'+id)?.addEventListener('click',()=>openDialog('#project-dialog'))}
function renderSources(){const project=activeProject(),content=$('#sources-content');if(!project){content.innerHTML=empty('▤','Najpierw utwórz projekt','Każde źródło należy do konkretnej drogi.','Utwórz projekt','sources-new-project');bindProjectEmpty('sources-new-project');return}const sources=project.sources||[];content.innerHTML=sources.length?`<div class="panel"><div class="panel-head"><h2>Materiały</h2><span class="counter">${sources.length}</span></div><div class="list">${sources.map(sourceRow).join('')}</div></div>`:empty('▤','Brak źródeł','Dodaj pierwszy materiał bez gotowych przykładów i sztucznego wypełniania.','Dodaj źródło','sources-add-first');$('#sources-add-first')?.addEventListener('click',openSourceDialog)}
function timeLabel(type){return({exact:'dokładnie',approx:'około',before:'przed',after:'po',parallel:'równolegle',order:'kolejność',unknown:'nieustalone'})[type]||'nieustalone'}
function eventRow(event){const project=activeProject(),sources=eventSources(event),primary=sources.find(source=>source.id===event.sourceId)||sources[0],characters=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)),related=(project.events||[]).find(item=>item.id===event.relationEventId),relation=related?`<small class="event-relation">↳ ${timeLabel(event.timeType)}: ${escapeHtml(related.title)}</small>`:'',effectiveDate=event.date||sources.map(source=>source.date).filter(Boolean).sort()[0],worldLinks=(event.worldLinks||[]).filter(name=>name&&name!==event.world),meeting=worldLinks.length?`<span class="tag convergence-tag">spotkanie: ${escapeHtml(worldLinks.join(' + '))}</span>`:'',sourceNames=sources.map(source=>source.title).join(' · ');return `<article class="list-item"><span class="list-mark">●</span><div class="list-copy"><b>${escapeHtml(event.title)}</b><small>${escapeHtml(sourceNames||'Bez przypisanego źródła')} · ${dateLabel(effectiveDate,event.date?event.timeType==='approx':primary?.dateApprox)}</small>${relation}<div class="tag-row">${event.world?`<span class="tag">${escapeHtml(event.world)}</span>`:''}${meeting}${event.place?`<span class="tag">${escapeHtml(event.place)}</span>`:''}${characters.map(character=>`<span class="tag character-tag">♙ ${escapeHtml(character.name)}</span>`).join('')}${event.inbox?'<span class="tag inbox-tag">do uporządkowania</span>':''}</div></div><span class="status">${timeLabel(event.timeType)}</span>${itemActions('event',event.id)}</article>`}
function renderEvents(){const project=activeProject(),content=$('#events-content');if(!project){content.innerHTML=empty('●','Najpierw utwórz projekt','Wydarzenia będą zapisywane wewnątrz wybranej kroniki.','Utwórz projekt','events-new-project');bindProjectEmpty('events-new-project');return}const events=(project.events||[]).slice().reverse();content.innerHTML=events.length?`<div class="panel"><div class="panel-head"><h2>Dziennik wydarzeń</h2><span class="counter">${events.length}</span></div><div class="list">${events.map(eventRow).join('')}</div></div>`:empty('●','Dziennik jest pusty','Jedno zdanie wystarczy. Świat, miejsce i chronologię możesz dopisać później.','Dodaj wydarzenie','events-add-first');$('#events-add-first')?.addEventListener('click',openEventDialog)}
function characterConnections(characterId){const project=activeProject(),events=(project?.events||[]).filter(event=>(event.characterIds||[]).includes(characterId)),ids=new Set(events.flatMap(event=>event.characterIds||[]).filter(id=>id!==characterId));return{events,characters:projectCharacters().filter(character=>ids.has(character.id))}}
function characterRow(character){const links=characterConnections(character.id),life=[character.birthDate||'?',character.deathDate||'…'].join(' – ');return `<article class="list-item character-item"><span class="list-mark">♙</span><div class="list-copy"><b>${escapeHtml(character.name)}</b><small>${escapeHtml(character.alterEgo||'Bez alter ego')} · ${escapeHtml(character.world||'świat nieustalony')} · ${escapeHtml(life)}</small><div class="tag-row">${links.characters.slice(0,6).map(item=>`<span class="tag connection-tag">↔ ${escapeHtml(item.name)}</span>`).join('')}</div></div><span class="status">${links.characters.length} koneksji</span>${itemActions('character',character.id)}</article>`}
function renderCharacters(){const project=activeProject(),content=$('#characters-content');if(!project){content.innerHTML=empty('♙','Najpierw utwórz projekt','Postacie będą należały do wybranej kroniki.','Utwórz projekt','characters-new-project');bindProjectEmpty('characters-new-project');return}const characters=projectCharacters();content.innerHTML=characters.length?`<div class="panel"><div class="panel-head"><h2>Kartoteka postaci</h2><span class="counter">${characters.length}</span></div><div class="list">${characters.map(characterRow).join('')}</div></div>`:empty('♙','Brak postaci','Dodaj postać, a następnie przypisuj ją bezpośrednio do wydarzeń.','Dodaj postać','characters-add-first');$('#characters-add-first')?.addEventListener('click',()=>openCharacterDialog())}
function renderAtlas(){const project=activeProject(),events=project?.events||[],worlds=project?projectWorlds():[],connections=events.flatMap(event=>(event.worldLinks||[]).filter(name=>name&&name!==event.world).map(name=>({from:event.world||'Świat nieustalony',to:name,event:event.title})));if(!project||!worlds.length){$('#atlas-content').innerHTML=`<div class="atlas-placeholder"><div class="atlas-grid"></div><div class="atlas-message"><div><div class="empty-icon">⌖</div><h2>${project?'Atlas czeka na światy':'Najpierw utwórz projekt'}</h2><p>${project?'Dodaj pierwszy świat w widoku Road. Każdy pozostanie osobnym węzłem, nawet gdy później spotka się z innym.':'Atlas należy do wybranego projektu i pozostaje całkowicie pusty.'}</p></div></div></div>`;return}$('#atlas-content').innerHTML=`<div class="world-network"><div class="panel-head"><h2>Wszystkie połączone światy</h2><span class="counter">${worlds.length}</span></div><div class="world-nodes">${worlds.map((world,index)=>`<article class="world-node" style="--world-index:${index}"><span>◉</span><b>${escapeHtml(worldLabel(world))}</b><small>${escapeHtml(world.description||'Osobna gałąź projektu')}</small></article>`).join('')}</div><div class="world-bridges">${connections.length?connections.map(link=>`<article><span>${escapeHtml(link.from)}</span><i>→</i><span>${escapeHtml(link.to)}</span><b>${escapeHtml(link.event)}</b></article>`).join(''):'<p class="panel-note">Światy są jeszcze rozdzielone. Spotkanie zapisane w wydarzeniu utworzy tutaj most.</p>'}</div></div>`}
function updateActions(){const hasProject=Boolean(activeProject());$('#quick-event-button').disabled=!hasProject;$('#add-source-button').disabled=!hasProject;$('#add-character-button').disabled=!hasProject;$('#add-event-button').disabled=!hasProject}
function render(){renderProjectSelect();renderRoad();renderSources();renderCharacters();renderEvents();renderAtlas();updateActions()}
function switchView(view){$$('.view').forEach(section=>section.classList.toggle('active',section.id==='view-'+view));$$('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
function ensureCharacterDialog(){if($('#character-dialog'))return;const dialog=document.createElement('dialog');dialog.id='character-dialog';dialog.className='dialog';dialog.innerHTML='<form id="character-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">POSTAĆ</p><h2>Dodaj postać</h2><label>Nazwa<input id="character-name" required autocomplete="off"></label><label>Alter ego<input id="character-alter-ego" autocomplete="off"></label><label>Świat<input id="character-world" list="project-world-list" autocomplete="off"></label><div class="form-row"><label>Data urodzenia<input id="character-birth" type="date"></label><label>Data śmierci<input id="character-death" type="date"></label></div><button class="primary-button full" value="save" type="submit">Dodaj postać</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const name=$('#character-name').value.trim();if(!name)return;const data={name,alterEgo:$('#character-alter-ego').value.trim(),world:$('#character-world').value.trim(),birthDate:$('#character-birth').value,deathDate:$('#character-death').value};if(editingCharacterId){const item=projectCharacters().find(character=>character.id===editingCharacterId);if(item)Object.assign(item,data)}else projectCharacters().push({id:uid('character'),...data});editingCharacterId=null;save();dialog.close();render()})}
function openCharacterDialog(characterId=null){if(!activeProject())return openDialog('#project-dialog');ensureWorldFields();ensureCharacterDialog();editingCharacterId=characterId;$('#character-form').reset();const item=projectCharacters().find(character=>character.id===characterId);if(item){$('#character-name').value=item.name;$('#character-alter-ego').value=item.alterEgo||'';$('#character-world').value=item.world||'';$('#character-birth').value=item.birthDate||'';$('#character-death').value=item.deathDate||'';$('#character-dialog h2').textContent='Edytuj postać';$('#character-form .primary-button').textContent='Zapisz zmiany'}else{$('#character-dialog h2').textContent='Dodaj postać';$('#character-form .primary-button').textContent='Dodaj postać'}openDialog('#character-dialog')}
function ensureWorldDialog(){if($('#world-dialog'))return;const dialog=document.createElement('dialog');dialog.id='world-dialog';dialog.className='dialog';dialog.innerHTML='<form id="world-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">NOWY ŚWIAT</p><h2>Dodaj świat do projektu</h2><label>Numer rzeczywistości<div class="world-number-input"><span>Earth-</span><input id="world-number" required inputmode="numeric" autocomplete="off" placeholder="616"></div></label><label>Krótki opis<input id="world-description" required autocomplete="off" placeholder="Np. MCU, główne komiksy Marvela, X-Men Foxa"></label><button class="primary-button full" value="save" type="submit">Dodaj świat</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const number=$('#world-number').value.trim().replace(/^earth-/i,''),description=$('#world-description').value.trim(),label=`Earth-${number}`;if(!number||!description||projectWorlds().some(world=>worldLabel(world).toLowerCase()===label.toLowerCase()))return;projectWorlds().push({id:uid('world'),number,name:label,description});save();dialog.close();render()})}
function openWorldDialog(){if(!activeProject())return openDialog('#project-dialog');ensureWorldDialog();$('#world-form').reset();openDialog('#world-dialog')}
function ensureWorldFields(){ensureDateFields();let list=$('#project-world-list');if(!list){list=document.createElement('datalist');list.id='project-world-list';document.body.append(list);$('#event-world').setAttribute('list','project-world-list')}list.innerHTML=projectWorlds().map(world=>`<option value="${escapeHtml(worldLabel(world))}">${escapeHtml(world.description||'')}</option>`).join('');let links=$('#event-world-links');if(!links){links=document.createElement('fieldset');links.id='event-world-links';links.className='world-links';$('#event-world').closest('.form-row').after(links)}links.innerHTML='<legend>Światy uczestniczące w spotkaniu</legend><p>Zaznacz dodatkowe światy, których linie łączą się w tym wydarzeniu.</p><div>'+projectWorlds().map(world=>`<label><input type="checkbox" value="${escapeHtml(worldLabel(world))}"> ${escapeHtml(worldLabel(world))} · ${escapeHtml(world.description||'')}</label>`).join('')+'</div>';ensureCharacterFields()}
function ensureCharacterFields(){let field=$('#event-characters');if(!field){field=document.createElement('fieldset');field.id='event-characters';field.className='event-characters';$('#event-extra-sources').after(field)}field.innerHTML='<legend>Postacie uczestniczące w wydarzeniu</legend><div>'+projectCharacters().map(character=>`<label><input type="checkbox" value="${character.id}"> ${escapeHtml(character.name)}${character.alterEgo?' / '+escapeHtml(character.alterEgo):''}</label>`).join('')+'</div>';const item=activeProject()?.events.find(event=>event.id===editingEventId);if(item)field.querySelectorAll('input').forEach(input=>input.checked=(item.characterIds||[]).includes(input.value))}
function ensureDateFields(){if(!$('#source-date-row')){const row=document.createElement('div');row.id='source-date-row';row.className='form-row';row.innerHTML='<label>Data źródła<input id="source-date" type="date"></label><label class="check date-check"><input id="source-date-approx" type="checkbox"> Data przybliżona</label>';$('#source-status').closest('.form-row').after(row)}if(!$('#event-date-row')){const row=document.createElement('div');row.id='event-date-row';row.className='form-row event-date-row';row.hidden=true;row.innerHTML='<label>Data wydarzenia<input id="event-date" type="date"></label><label><span>Dziedziczenie daty</span><small>Jeśli pole zostanie puste, wydarzenie użyje daty źródła.</small></label>';$('#event-time-type').closest('.form-row').after(row)}}
function renderEventDateField(){const row=$('#event-date-row');if(row)row.hidden=!['exact','approx'].includes($('#event-time-type').value)}
function openSourceDialog(sourceId=null){if(!activeProject())return openDialog('#project-dialog');editingSourceId=sourceId;ensureDateFields();$('#source-form').reset();if(sourceId){const item=activeProject().sources.find(source=>source.id===sourceId);if(item){$('#source-title').value=item.title;$('#source-type').value=item.type;$('#source-status').value=item.status;$('#source-date').value=item.date||'';$('#source-date-approx').checked=Boolean(item.dateApprox);$('#source-dialog h2').textContent='Edytuj źródło';$('#source-form .primary-button').textContent='Zapisz zmiany'}}else{$('#source-dialog h2').textContent='Dodaj materiał';$('#source-form .primary-button').textContent='Dodaj do Road'}openDialog('#source-dialog')}
function populateEventSources(){const select=$('#event-source'),sources=activeProject()?.sources||[];select.previousSibling&&(select.closest('label').childNodes[0].textContent='Źródło główne');select.innerHTML='<option value="">Bez źródła głównego</option>';sources.forEach(source=>{const option=document.createElement('option');option.value=source.id;option.textContent=source.title;select.append(option)});let extra=$('#event-extra-sources');if(!extra){extra=document.createElement('fieldset');extra.id='event-extra-sources';extra.className='extra-sources';select.closest('.form-row').after(extra)}extra.innerHTML='<legend>Dodatkowe źródła tego samego wydarzenia</legend><div>'+sources.map(source=>`<label><input type="checkbox" value="${source.id}"> ${escapeHtml(source.title)}</label>`).join('')+'</div>'}
function ensureRelationPicker(){if($('#event-relation-picker'))return;const panel=document.createElement('section');panel.id='event-relation-picker';panel.className='relation-picker';panel.hidden=true;panel.innerHTML='<div class="relation-head"><div><b>Wybierz powiązane wydarzenie</b><small>Wyszukaj nazwę, postać, tag, świat lub miejsce</small></div><span id="relation-count"></span></div><input id="event-relation-search" type="search" autocomplete="off" placeholder="Szukaj wydarzenia lub osoby…"><div id="event-relation-results" class="relation-results"></div><p id="event-relation-error" class="relation-error" hidden>Wybierz wydarzenie, z którym tworzysz relację.</p>';const anchor=$('#event-world').closest('.form-row');anchor.before(panel);$('#event-relation-search').addEventListener('input',renderRelationPicker)}
function relationHaystack(event){const names=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)).flatMap(character=>[character.name,character.alterEgo]);return [event.title,event.world,event.place,event.notes,...eventSources(event).map(source=>source.title),...names,...(event.tags||[])].filter(Boolean).join(' ').toLowerCase()}
function renderRelationPicker(){const panel=$('#event-relation-picker');if(!panel)return;const type=$('#event-time-type').value,visible=RELATION_TYPES.has(type);panel.hidden=!visible;if(!visible){selectedRelationId=null;return}const project=activeProject(),query=$('#event-relation-search').value.trim().toLowerCase(),events=(project?.events||[]).filter(event=>!query||relationHaystack(event).includes(query)),sources=project?.sources||[],groups=new Map();events.forEach(event=>{const key=event.sourceId||'';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(event)});$('#relation-count').textContent=events.length+' wyników';const results=$('#event-relation-results');if(!events.length){results.innerHTML='<div class="relation-empty">Nie znaleziono pasującego wydarzenia.</div>';return}const ordered=[...sources.map(source=>source.id),''].filter((id,index,array)=>groups.has(id)&&array.indexOf(id)===index);results.innerHTML=ordered.map(sourceId=>{const source=sources.find(item=>item.id===sourceId),items=groups.get(sourceId)||[];return `<div class="relation-group"><p>${escapeHtml(source?.title||'Bez przypisanego źródła')}</p>${items.map(event=>`<button class="relation-option${event.id===selectedRelationId?' selected':''}" type="button" data-event-id="${event.id}"><b>${escapeHtml(event.title)}</b><small>${escapeHtml([...(event.tags||[]),event.world,event.place].filter(Boolean).join(' · ')||'Bez dodatkowych tagów')}</small></button>`).join('')}</div>`}).join('');results.querySelectorAll('.relation-option').forEach(button=>button.addEventListener('click',()=>{selectedRelationId=button.dataset.eventId;$('#event-relation-error').hidden=true;renderRelationPicker()}))}
function openEventDialog(eventId=null){if(!activeProject())return openDialog('#project-dialog');editingEventId=eventId;ensureWorldFields();$('#event-form').reset();$('#event-inbox').checked=true;selectedRelationId=null;populateEventSources();ensureCharacterFields();ensureRelationPicker();$('#event-relation-search').value='';if(eventId){const item=activeProject().events.find(event=>event.id===eventId);if(item){$('#event-title').value=item.title;$('#event-source').value=item.sourceId||'';$('#event-time-type').value=item.timeType||'unknown';$('#event-date').value=item.date||'';$('#event-world').value=item.world||'';$('#event-place').value=item.place||'';$('#event-tags').value=(item.tags||[]).join(', ');$('#event-notes').value=item.notes||'';$('#event-inbox').checked=Boolean(item.inbox);selectedRelationId=item.relationEventId||null;$('#event-dialog h2').textContent='Edytuj wydarzenie';$('#event-form .primary-button').textContent='Zapisz zmiany';$('#event-extra-sources').querySelectorAll('input').forEach(input=>input.checked=eventSourceIds(item).includes(input.value)&&input.value!==item.sourceId);$('#event-world-links').querySelectorAll('input').forEach(input=>input.checked=(item.worldLinks||[]).includes(input.value));$('#event-characters').querySelectorAll('input').forEach(input=>input.checked=(item.characterIds||[]).includes(input.value))}}else{$('#event-dialog h2').textContent='Co się wydarzyło?';$('#event-form .primary-button').textContent='Zapisz i dodaj następne'}renderEventDateField();renderRelationPicker();openDialog('#event-dialog')}

$$('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$$('.dialog-close').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close()}));
$('#brand-home').addEventListener('click',()=>switchView('road'));
$('#theme-button').addEventListener('click',()=>document.body.classList.toggle('light'));
$('#new-project-main').addEventListener('click',()=>activeProject()?openSourceDialog():openDialog('#project-dialog'));
$('#new-project-side').addEventListener('click',()=>openDialog('#project-dialog'));
$('#quick-event-button').addEventListener('click',openEventDialog);$('#add-event-button').addEventListener('click',openEventDialog);$('#add-source-button').addEventListener('click',openSourceDialog);$('#add-character-button').addEventListener('click',()=>openCharacterDialog());
$('#event-time-type').addEventListener('change',()=>{ensureDateFields();ensureRelationPicker();renderEventDateField();renderRelationPicker()});
$('#project-select').addEventListener('change',event=>{state.activeProjectId=event.target.value||null;save();render()});
$('.main').addEventListener('click',event=>{const button=event.target.closest('button[data-id]');if(!button)return;const project=activeProject(),id=button.dataset.id;if(button.classList.contains('edit-source'))openSourceDialog(id);if(button.classList.contains('edit-event'))openEventDialog(id);if(button.classList.contains('edit-character'))openCharacterDialog(id);if(button.classList.contains('delete-source')&&confirm('Usunąć to źródło? Powiązane wydarzenia pozostaną w projekcie.')){project.sources=project.sources.filter(source=>source.id!==id);project.events.forEach(item=>{if(item.sourceId===id)item.sourceId=null;item.sourceIds=eventSourceIds(item).filter(sourceId=>sourceId!==id)});save();render()}if(button.classList.contains('delete-event')&&confirm('Usunąć to wydarzenie?')){project.events=project.events.filter(item=>item.id!==id);project.events.forEach(item=>{if(item.relationEventId===id)item.relationEventId=null});save();render()}if(button.classList.contains('delete-character')&&confirm('Usunąć tę postać? Zniknie także z przypisanych wydarzeń.')){project.characters=projectCharacters().filter(character=>character.id!==id);project.events.forEach(item=>item.characterIds=(item.characterIds||[]).filter(characterId=>characterId!==id));save();render()}});
$('#project-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const name=$('#project-name').value.trim();if(!name)return;const project={id:uid('project'),name,description:$('#project-description').value.trim(),createdAt:new Date().toISOString(),worlds:[],sources:[],characters:[],events:[]};state.projects.push(project);state.activeProjectId=project.id;save();event.currentTarget.reset();$('#project-dialog').close();render();switchView('road')});
$('#source-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#source-title').value.trim();if(!project||!title)return;const data={title,type:$('#source-type').value,status:$('#source-status').value,date:$('#source-date')?.value||'',dateApprox:$('#source-date-approx')?.checked||false};if(editingSourceId){const item=project.sources.find(source=>source.id===editingSourceId);if(item)Object.assign(item,data)}else project.sources.push({id:uid('source'),...data,createdAt:new Date().toISOString()});editingSourceId=null;save();event.currentTarget.reset();$('#source-dialog').close();render();switchView('road')});
$('#event-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#event-title').value.trim(),timeType=$('#event-time-type').value;if(!project||!title)return;if(RELATION_TYPES.has(timeType)&&!selectedRelationId){$('#event-relation-error').hidden=false;$('#event-relation-picker').scrollIntoView({block:'nearest'});return}const sourceId=$('#event-source').value||null,extraSources=[...$('#event-extra-sources').querySelectorAll('input:checked')].map(input=>input.value).filter(id=>id!==sourceId),data={title,sourceId,sourceIds:[sourceId,...extraSources].filter(Boolean),characterIds:[...$('#event-characters').querySelectorAll('input:checked')].map(input=>input.value),timeType,date:$('#event-date')?.value||'',relationEventId:selectedRelationId,world:$('#event-world').value.trim(),worldLinks:[...$('#event-world-links').querySelectorAll('input:checked')].map(input=>input.value),place:$('#event-place').value.trim(),tags:$('#event-tags').value.split(',').map(tag=>tag.trim()).filter(Boolean),notes:$('#event-notes').value.trim(),inbox:$('#event-inbox').checked};if(editingEventId){const item=project.events.find(existing=>existing.id===editingEventId);if(item)Object.assign(item,data);editingEventId=null;save();$('#event-dialog').close();render();return}project.events.push({id:uid('event'),...data,createdAt:new Date().toISOString()});save();event.currentTarget.reset();selectedRelationId=null;populateEventSources();ensureCharacterFields();$('#event-source').value=sourceId||'';$('#event-inbox').checked=true;renderEventDateField();renderRelationPicker();render();$('#event-title').focus()});

render();switchView('road');
