const STORAGE_KEY='chronizo.workbench.v1';
const THEME_KEY='chronizo.theme';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const freshState=()=>({projects:[],activeProjectId:null});
let state=load();
let selectedRelationId=null;
let roadMode='sources';
let sourceTagFilter='all';
let sourceColorMode='medium';
let sourceVisibleLimit=160;
let selectedCharacterId=null;
let editingSourceId=null;
let editingEventId=null;
let editingCharacterId=null;
let worldDialogTarget=null;
let sourceDialogTarget=null;
let characterDialogTarget=null;
const RELATION_TYPES=new Set(['before','after','parallel']);

function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return parsed&&Array.isArray(parsed.projects)?parsed:freshState()}catch{return freshState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function activeProject(){return state.projects.find(project=>project.id===state.activeProjectId)||null}
function projectWorlds(){const project=activeProject();if(!project)return[];return project.worlds||(project.worlds=[])}
function worldLabel(world){return world.designation||(world.number?`Earth-${world.number}`:world.name)||'Świat bez oznaczenia'}
function projectCharacters(){const project=activeProject();if(!project)return[];return project.characters||(project.characters=[])}
function characterAliases(character){return [...new Set([...(character.aliases||[]),character.alterEgo].filter(Boolean))]}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function openDialog(selector){const dialog=$(selector);dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type="checkbox"]),textarea,select')?.focus())}
function applyTheme(theme=localStorage.getItem(THEME_KEY)||'green'){document.body.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);const names={shield:'Tarcza Kapitana',green:'Zielony Chronizo',dark:'Ciemny',light:'Jasny'};$('#theme-button').title=`Motyw: ${names[theme]||names.green}`;$('#theme-button').textContent=theme==='shield'?'⭑':theme==='light'?'☀':theme==='dark'?'◐':'◉'}
function ensureThemeDialog(){if($('#theme-dialog'))return;const dialog=document.createElement('dialog');dialog.id='theme-dialog';dialog.className='dialog theme-dialog';dialog.innerHTML='<form method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">WYGLĄD</p><h2>Wybierz motyw Chronizo</h2><div class="theme-options"><button type="button" data-theme-choice="shield"><i></i><b>Tarcza Kapitana</b><small>Czerwień, biel i granat</small></button><button type="button" data-theme-choice="green"><i></i><b>Zielony Chronizo</b><small>Dotychczasowy wygląd</small></button><button type="button" data-theme-choice="dark"><i></i><b>Ciemny</b><small>Neutralna nocna kronika</small></button><button type="button" data-theme-choice="light"><i></i><b>Jasny</b><small>Do czytania w dzień</small></button></div></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelectorAll('[data-theme-choice]').forEach(button=>button.onclick=()=>{applyTheme(button.dataset.themeChoice);dialog.close()})}
function openThemeDialog(){ensureThemeDialog();openDialog('#theme-dialog')}
function empty(icon,title,copy,action='',buttonId=''){return `<div class="empty-state"><div class="empty-state-inner"><div class="empty-icon">${icon}</div><h2>${title}</h2><p>${copy}</p>${action?`<button id="${buttonId}" class="primary-button" type="button">${action}</button>`:''}</div></div>`}

function renderProjectSelect(){const select=$('#project-select');select.innerHTML='';if(!state.projects.length){const option=document.createElement('option');option.textContent='Brak projektu';option.value='';select.append(option);select.disabled=true;return}select.disabled=false;state.projects.forEach(project=>{const option=document.createElement('option');option.value=project.id;option.textContent=project.name;option.selected=project.id===state.activeProjectId;select.append(option)})}
function dateLabel(value,approx=false){if(!value)return 'data nieustalona';return (approx?'około ':'')+escapeHtml(value)}
function itemActions(type,id){return `<div class="item-actions"><button class="edit-${type}" data-id="${id}" type="button" title="Edytuj">✎</button><button class="delete-${type}" data-id="${id}" type="button" title="Usuń">×</button></div>`}
function releaseLabel(value){return value?`premiera: ${escapeHtml(value)}`:'premiera nieustalona'}
function sourceWorldLabels(source){const ids=new Set(source.worldIds||[]);return projectWorlds().filter(world=>ids.has(world.id)).map(worldLabel)}
function sourceTags(source){return [...new Set((source.tags||[]).map(tag=>String(tag).trim().toUpperCase()).filter(Boolean))]}
function importSheetPosition(key=''){const match=String(key).match(/^(extended|multiversal)-vo-(\d+)$/);return match?{tag:match[1]==='extended'?'EMCU':'MVO',row:Number(match[2])}:null}
function rememberSheetPosition(source,tag,row){if(!Number.isFinite(Number(row)))return false;source.sheetRows=source.sheetRows||{};if(source.sheetRows[tag]===Number(row))return false;source.sheetRows[tag]=Number(row);return true}
function migrateLegacySourceTags(){let changed=false;for(const project of state.projects){for(const source of project.sources||[]){const keys=[source.importKey,...(source.importKeys||[])].filter(Boolean),tags=sourceTags(source),legacyTag=source.importOrigin==='Extended VO'||keys.some(key=>key.startsWith('extended-vo-'))?'EMCU':source.importOrigin==='Multiversal VO'||keys.some(key=>key.startsWith('multiversal-vo-'))?'MVO':null;if(legacyTag&&!tags.includes(legacyTag)){source.tags=[...tags,legacyTag];changed=true}for(const key of keys){const position=importSheetPosition(key);if(position)changed=rememberSheetPosition(source,position.tag,position.row)||changed}}}if(changed)save()}
function metadataKey(value=''){return String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘]/g,"'").replace(/[–—]/g,'-').replace(/\s+/g,' ').trim()}
function universeMetadataKey(value=''){return metadataKey(value).replace(/^earth-/,'').replace(/[✩★*]+$/,'').replace(/\s+/g,'')}
function universeMetadataAliases(value=''){const aliases=[];for(const part of String(value).split('/').map(item=>item.trim()).filter(Boolean)){aliases.push(part);const aka=part.match(/^(.+?)\s*\(AKA\s+(.+?)\)$/i);if(aka)aliases.push(aka[1],aka[2])}return [...new Set(aliases.map(universeMetadataKey).filter(Boolean))]}
function releaseDateIso(value=''){const months={jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'},match=String(value).trim().match(/^([A-Za-z]{3})\s+(\d{1,2}),\s*(\d{4})$/);return match&&months[match[1].toLowerCase()]?`${match[3]}-${months[match[1].toLowerCase()]}-${String(match[2]).padStart(2,'0')}`:''}
async function enrichSourceMetadata(){try{const response=await fetch('data/source-metadata.json?v=1');if(!response.ok)return;const metadata=await response.json();if(metadata.format!=='chronizo-source-metadata')return;const releases=new Map();for(const release of metadata.releases||[]){const key=metadataKey(release.title);if(!releases.has(key))releases.set(key,release)}const universes=new Map();for(const universe of metadata.universes||[])for(const key of universeMetadataAliases(universe.designation))if(!universes.has(key))universes.set(key,universe);let changed=false;for(const project of state.projects){for(const source of project.sources||[]){const imported=[source.importKey,...(source.importKeys||[])].some(key=>importSheetPosition(key));if(!imported||source.releaseDate)continue;const release=releases.get(metadataKey(source.title)),date=releaseDateIso(release?.date);if(date){source.releaseDate=date;source.releaseOrderRow=release.row;changed=true}}for(const world of project.worlds||[]){const importedDescription=!world.description||/ · import$/i.test(world.description);if(!importedDescription)continue;const universe=universes.get(universeMetadataKey(worldLabel(world)));if(universe?.description&&world.description!==universe.description){world.description=universe.description;world.universeIndexRow=universe.row;changed=true}}}if(changed){save();render()}}catch(error){console.warn('Chronizo metadata enrichment skipped',error)}}
function sourceTagMarkup(source){return sourceTags(source).map(tag=>`<span class="tag source-hashtag">#${escapeHtml(tag)}</span>`).join('')}
function sourcePalette(source){const medium={Film:'#2f76ff',Serial:'#8b5cf6',Komiks:'#ef4444',Książka:'#d79b19',Gra:'#18a96b',Inne:'#32a4ad'},tag={EMCU:'#2374d8',MVO:'#8a4fd1'},colors=sourceColorMode==='tag'?sourceTags(source).map(name=>tag[name]||'#38bfa1'):[medium[source.type]||medium.Inne],strength=source.status==='Ukończone'||source.status==='Opracowane'?42:source.status==='Rozpoczęte'?24:9,mixes=(colors.length?colors:['#32a4ad']).map(color=>`color-mix(in srgb,${color} ${strength}%,var(--panel2))`);return `--source-bg:${mixes.length>1?`linear-gradient(120deg,${mixes.join(',')})`:mixes[0]};--source-accent:${colors[0]||'#32a4ad'}`}
function sourceRow(source){const worlds=sourceWorldLabels(source);return `<article class="list-item source-item" style="${sourcePalette(source)}"><span class="list-mark">▤</span><div class="list-copy"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)} · akcja: ${dateLabel(source.date,source.dateApprox)} · ${releaseLabel(source.releaseDate)}</small><div class="tag-row">${sourceTagMarkup(source)}${worlds.map(world=>`<span class="tag">${escapeHtml(world)}</span>`).join('')}</div></div><span class="status">${escapeHtml(source.status)}</span>${itemActions('source',source.id)}</article>`}
function allSourceTags(){return [...new Set((activeProject()?.sources||[]).flatMap(sourceTags))].sort()}
function filteredSources(){const sources=activeProject()?.sources||[];return sourceTagFilter==='all'?sources:sources.filter(source=>sourceTags(source).includes(sourceTagFilter))}
function sourceControls(){const tags=allSourceTags();return `<div class="source-controls"><div class="source-tag-filters"><button class="${sourceTagFilter==='all'?'active':''}" data-source-tag="all" type="button">Wszystkie</button>${tags.map(tag=>`<button class="${sourceTagFilter===tag?'active':''}" data-source-tag="${escapeHtml(tag)}" type="button">#${escapeHtml(tag)}</button>`).join('')}</div><label>Kolor tła<select data-source-color><option value="medium" ${sourceColorMode==='medium'?'selected':''}>według medium</option><option value="tag" ${sourceColorMode==='tag'?'selected':''}>według hashtagu</option></select></label></div>`}
function bindSourceControls(root=document){root.querySelectorAll('[data-source-tag]').forEach(button=>button.addEventListener('click',()=>{sourceTagFilter=button.dataset.sourceTag;sourceVisibleLimit=160;renderSources();renderRoad()}));root.querySelectorAll('[data-source-color]').forEach(select=>select.addEventListener('change',()=>{sourceColorMode=select.value;renderSources();renderRoad()}))}
function eventSourceIds(event){return [...new Set([event.sourceId,...(event.sourceIds||[])].filter(Boolean))]}
function eventSources(event){const ids=eventSourceIds(event);return (activeProject()?.sources||[]).filter(source=>ids.includes(source.id))}
function chronologyKey(value=''){const text=String(value).trim(),normalized=text.replace(/,/g,'');if(!text)return Number.POSITIVE_INFINITY;if(/^(beginning of time|początek czasu)$/i.test(text))return Number.NEGATIVE_INFINITY;let match=normalized.match(/^(-?\d+(?:\.\d+)?)\s*(BC|BCE|p\.n\.e\.)$/i);if(match)return-Number(match[1]);match=normalized.match(/^(-?\d+(?:\.\d+)?)\s*(AD|CE|n\.e\.)?$/i);if(match)return Number(match[1]);match=text.match(/^(-?\d{1,6})-(\d{2})-(\d{2})$/);if(match)return Number(match[1])+Number(match[2])/12+Number(match[3])/372;return Number.POSITIVE_INFINITY}
function sourceSheetRow(source){const rows=source.sheetRows||{},preferred=sourceTagFilter!=='all'?rows[sourceTagFilter]:rows.EMCU??rows.MVO;if(Number.isFinite(Number(preferred)))return Number(preferred);const positions=[source.importKey,...(source.importKeys||[])].map(importSheetPosition).filter(Boolean),match=sourceTagFilter==='all'?positions.find(position=>position.tag==='EMCU')||positions.find(position=>position.tag==='MVO'):positions.find(position=>position.tag===sourceTagFilter);return match?.row??Number.POSITIVE_INFINITY}
function chronologicalCompare(a,b){const difference=chronologyKey(a.date)-chronologyKey(b.date);if(!Number.isNaN(difference)&&difference!==0)return difference;const sheetDifference=sourceSheetRow(a)-sourceSheetRow(b);return !Number.isNaN(sheetDifference)&&sheetDifference!==0?sheetDifference:(a.createdAt||'').localeCompare(b.createdAt||'')}
function earliestDate(values){return values.filter(Boolean).sort((a,b)=>chronologyKey(a)-chronologyKey(b))[0]||''}
function eventChronologyDate(event){return event.date||earliestDate(eventSources(event).map(source=>source.date))}
function orderEventsChronologically(events){const ordered=events.slice().sort((a,b)=>{const difference=chronologyKey(eventChronologyDate(a))-chronologyKey(eventChronologyDate(b));return Number.isNaN(difference)||difference===0?(a.createdAt||'').localeCompare(b.createdAt||''):difference});for(let pass=0;pass<ordered.length*2;pass++){let changed=false;for(const event of [...ordered]){if(!RELATION_TYPES.has(event.timeType)||!event.relationEventId)continue;const from=ordered.indexOf(event),target=ordered.findIndex(item=>item.id===event.relationEventId);if(target<0)continue;const wantsBefore=event.timeType==='before',wrong=wantsBefore?from>target:event.timeType==='after'?from<target:Math.abs(from-target)>1;if(!wrong)continue;ordered.splice(from,1);const nextTarget=ordered.findIndex(item=>item.id===event.relationEventId);ordered.splice(wantsBefore?nextTarget:nextTarget+1,0,event);changed=true}if(!changed)break}return ordered}
function roadNode(item,index){if(roadMode==='sources')return `<article class="road-node source-item ${index%2?'branch-down':'branch-up'}" style="${sourcePalette(item)}"><span class="road-dot"></span><small>${dateLabel(item.date,item.dateApprox)}</small><b>${escapeHtml(item.title)}</b><em>${escapeHtml(item.type)} · ${escapeHtml(item.status)}<br>${releaseLabel(item.releaseDate)}</em><div class="tag-row">${sourceTagMarkup(item)}</div>${itemActions('source',item.id)}</article>`;const sources=eventSources(item),characters=projectCharacters().filter(character=>(item.characterIds||[]).includes(character.id));return `<article class="road-node ${index%2?'branch-down':'branch-up'}"><span class="road-dot"></span><small>${dateLabel(eventChronologyDate(item),item.timeType==='approx')}</small><b>${escapeHtml(item.title)}</b><em>${escapeHtml([item.world,item.place,...sources.map(source=>source.title)].filter(Boolean).join(' · ')||'Bez przypisania')}</em>${characters.length?`<span class="road-people">${characters.map(character=>escapeHtml(character.name)).join(' · ')}</span>`:''}${itemActions('event',item.id)}</article>`}
function roadItemsMarkup(items){if(roadMode!=='sources')return items.map(roadNode).join('');const groups=new Map();for(const source of items){const worlds=sourceWorldLabels(source).sort(),key=worlds.length?worlds.join(' + '):'Bez przypisanego świata';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(source)}return [...groups].sort(([a],[b])=>a.localeCompare(b,'pl')).map(([world,sources])=>`<section class="road-world-lane"><h3>${sources.some(source=>sourceWorldLabels(source).length>1)?'⇄ Połączenie · ':''}${escapeHtml(world)} <span>${sources.length}</span></h3><div class="road-lane-scroll"><div class="road-lane-track">${sources.map(roadNode).join('')}</div></div></section>`).join('')}
function exportProject(){const project=activeProject();if(!project)return;const payload={format:'chronizo-project',version:1,exportedAt:new Date().toISOString(),project},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(project.name||'chronizo').replace(/[^a-z0-9ąćęłńóśźż-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'.chronizo.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importProjectFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result),source=payload.format==='chronizo-project'?payload.project:payload;if(!source||typeof source.name!=='string'||!Array.isArray(source.sources)||!Array.isArray(source.events))throw new Error('Nieprawidłowy format');const project=structuredClone(source);project.id=uid('project');project.name=source.name+' · import';project.worlds=Array.isArray(project.worlds)?project.worlds:[];project.characters=Array.isArray(project.characters)?project.characters:[];state.projects.push(project);state.activeProjectId=project.id;save();render();switchView('road')}catch{alert('Nie udało się wczytać projektu. Wybierz plik JSON wyeksportowany z Chronizo.')}};reader.readAsText(file)}
function extendedUniverseLabels(value=''){return String(value).split('/').map(part=>part.trim()).filter(Boolean).map(part=>part==='FW'?'Framework':/^\d+[✩★]?$/.test(part)?`Earth-${part}`:part)}
function sourceIdentity(title,date,worlds){const normal=value=>String(value||'').toLowerCase().replace(/\s+/g,' ').trim();return [normal(title),normal(date),[...worlds].map(normal).sort().join('/')].join('|')}
async function importSourcePack({url,buttonId,label,tag}){const project=activeProject(),button=$(buttonId);if(!project)return openDialog('#project-dialog');button.disabled=true;button.textContent=`Wczytuję ${label}…`;try{const response=await fetch(url);if(!response.ok)throw new Error('Nie udało się pobrać paczki');const pack=await response.json();if(pack.format!=='chronizo-source-pack'||!Array.isArray(pack.sources))throw new Error('Nieprawidłowa paczka źródeł');let added=0,merged=0,worldsAdded=0;for(const packed of pack.sources){const labels=extendedUniverseLabels(packed.universe),worldIds=[];for(const designation of labels){let world=projectWorlds().find(item=>worldLabel(item).toLowerCase()===designation.toLowerCase());if(!world){world={id:uid('world'),designation,name:designation,description:`${label} · import`};projectWorlds().push(world);worldsAdded++}worldIds.push(world.id)}const identity=sourceIdentity(packed.title,packed.date,labels),byImport=(project.sources||[]).find(source=>source.importKey===packed.importKey||(source.importKeys||[]).includes(packed.importKey)),existing=byImport||(project.sources||[]).find(source=>sourceIdentity(source.title,source.date,sourceWorldLabels(source))===identity);if(existing){existing.tags=[...new Set([...sourceTags(existing),...(packed.tags||[]),tag].filter(Boolean))];existing.importKeys=[...new Set([...(existing.importKeys||[]),existing.importKey,packed.importKey].filter(Boolean))];existing.worldIds=[...new Set([...(existing.worldIds||[]),...worldIds])];rememberSheetPosition(existing,tag,packed.row);merged++;continue}project.sources.push({id:uid('source'),importKey:packed.importKey,importKeys:[packed.importKey],importOrigin:label,title:packed.title,type:packed.type||'Inne',status:'Nierozpoczęte',date:packed.date||'',dateApprox:Boolean(packed.dateApprox),releaseDate:packed.releaseDate||'',tags:[...new Set([...(packed.tags||[]),tag].filter(Boolean))],sheetRows:{[tag]:Number(packed.row)},worldIds,createdAt:new Date().toISOString()});added++}save();render();switchView('sources');alert(`${label}: dodano ${added}, połączono lub zaktualizowano ${merged}, utworzono ${worldsAdded} światów.`)}catch(error){alert(`Import ${label} nie powiódł się: ${error.message}`)}finally{button.disabled=false;button.textContent=`↓ Wczytaj ${label}`}}
async function importSourcePackFast({url,buttonId,label,tag}){
 const project=activeProject(),button=$(buttonId);
 if(!project)return openDialog('#project-dialog');
 button.disabled=true;button.textContent=`Wczytuję ${label}…`;
 try{
  const response=await fetch(url);if(!response.ok)throw new Error('Nie udało się pobrać paczki');
  const pack=await response.json();if(pack.format!=='chronizo-source-pack'||!Array.isArray(pack.sources))throw new Error('Nieprawidłowa paczka źródeł');
  const worlds=projectWorlds(),worldMap=new Map(worlds.map(world=>[worldLabel(world).toLowerCase(),world])),imports=new Map(),identities=new Map();
  for(const source of project.sources||[]){for(const key of [source.importKey,...(source.importKeys||[])].filter(Boolean))imports.set(key,source);identities.set(sourceIdentity(source.title,source.date,sourceWorldLabels(source)),source)}
  let added=0,merged=0,worldsAdded=0;
  for(const packed of pack.sources){
   const labels=extendedUniverseLabels(packed.universe),identity=sourceIdentity(packed.title,packed.date,labels);
   const existing=imports.get(packed.importKey)||identities.get(identity);
   if(existing){existing.tags=[...new Set([...sourceTags(existing),...(packed.tags||[]),tag].filter(Boolean))];existing.importKeys=[...new Set([...(existing.importKeys||[]),existing.importKey,packed.importKey].filter(Boolean))];rememberSheetPosition(existing,tag,packed.row);imports.set(packed.importKey,existing);identities.set(identity,existing);merged++;continue}
   const worldIds=[];
   for(const designation of labels){const key=designation.toLowerCase();let world=worldMap.get(key);if(!world){world={id:uid('world'),designation,name:designation,description:`${label} · import`};worlds.push(world);worldMap.set(key,world);worldsAdded++}worldIds.push(world.id)}
   const created={id:uid('source'),importKey:packed.importKey,importKeys:[packed.importKey],importOrigin:label,title:packed.title,type:packed.type||'Inne',status:'Nierozpoczęte',date:packed.date||'',dateApprox:Boolean(packed.dateApprox),releaseDate:packed.releaseDate||'',tags:[...new Set([...(packed.tags||[]),tag].filter(Boolean))],sheetRows:{[tag]:Number(packed.row)},worldIds,createdAt:new Date().toISOString()};
   project.sources.push(created);imports.set(packed.importKey,created);identities.set(identity,created);added++;
  }
  save();render();switchView('sources');void enrichSourceMetadata();alert(`${label}: dodano ${added}, połączono lub oznaczono hashtagami ${merged}, utworzono ${worldsAdded} światów.`);
 }catch(error){alert(`Import ${label} nie powiódł się: ${error.message}`)}
 finally{button.disabled=false;button.textContent=`↓ Wczytaj ${label}`}
}
function importExtendedVo(){return importSourcePackFast({url:'data/extended-vo.sources.json?v=2',buttonId:'#import-extended-vo',label:'Extended VO',tag:'EMCU'})}
function importMultiversalVo(){return importSourcePackFast({url:'data/multiversal-vo.sources.json?v=1',buttonId:'#import-multiversal-vo',label:'Multiversal VO',tag:'MVO'})}
function renderRoad(){
 const project=activeProject(),content=$('#road-content'),button=$('#new-project-main');
 if(!project){$('#road-title').textContent='Zacznij własną kronikę';$('#road-subtitle').textContent='Bez przykładów. Bez narzuconego uniwersum. To miejsce czeka na Twoją historię.';button.textContent='Utwórz pierwszy projekt';content.innerHTML=empty('◫','Tabula rasa','Utwórz projekt, nadaj mu własną nazwę i zacznij dodawać materiały. Chronizo nie wstawia żadnych przykładowych światów, postaci ani wydarzeń.','Utwórz projekt','empty-new-project');$('#empty-new-project').onclick=()=>openDialog('#project-dialog');return}
 const allSources=project.sources||[],allEvents=project.events||[],focusedCharacter=projectCharacters().find(character=>character.id===selectedCharacterId)||null,events=focusedCharacter?allEvents.filter(event=>(event.characterIds||[]).includes(focusedCharacter.id)):allEvents,sourceIds=new Set(events.flatMap(eventSourceIds)),sources=focusedCharacter?allSources.filter(source=>sourceIds.has(source.id)):allSources,inbox=events.filter(event=>event.inbox),orderedSources=filteredSources().filter(source=>!focusedCharacter||sourceIds.has(source.id)).slice().sort(chronologicalCompare),orderedEvents=orderEventsChronologically(events),allRoadItems=roadMode==='events'?orderedEvents:orderedSources,roadItems=roadMode==='sources'?allRoadItems.slice(0,300):allRoadItems;
 $('#road-title').textContent=project.name;$('#road-subtitle').textContent=project.description||'Twoja droga przez źródła i wydarzenia.';button.textContent='＋ Dodaj źródło';
 content.innerHTML=`<div class="road-top"><div class="road-modes" role="tablist" aria-label="Sposób budowania drogi"><button class="${roadMode==='sources'?'active':''}" data-road-mode="sources" type="button">▤ Według źródeł</button><button class="${roadMode==='events'?'active':''}" data-road-mode="events" type="button">● Chronologia wydarzeń</button></div><div class="project-data-actions"><button id="import-project" class="secondary-button" type="button">↑ Wczytaj JSON</button><button id="export-project" class="secondary-button" type="button">↓ Zapisz JSON</button><input id="import-project-file" type="file" accept="application/json,.json" hidden></div></div><div class="panel road-panel"><div class="panel-head"><h2>${roadMode==='events'?'Chronologia wydarzeń':'Kolejność źródeł według światów'}</h2><span class="counter">${roadItems.length}</span></div>${roadItems.length?`<div class="road-scroll"><div class="road-track">${roadItemsMarkup(roadItems)}</div></div>`:empty(roadMode==='events'?'●':'▤',roadMode==='events'?'Brak wydarzeń':'Droga jest jeszcze pusta',roadMode==='events'?'Dodaj pierwsze wydarzenie, aby zacząć budować chronologię.':'Dodaj pierwszy film, serial, komiks albo inne źródło.',roadMode==='events'?'Dodaj wydarzenie':'Dodaj źródło','road-add-item')}</div><div class="road-summary"><div class="panel"><div class="panel-head"><h2>Stan kroniki</h2></div><div class="metric-grid"><div class="metric"><strong>${sources.length}</strong><span>źródła</span></div><div class="metric"><strong>${events.length}</strong><span>wydarzenia</span></div><div class="metric"><strong>${inbox.length}</strong><span>do uporządkowania</span></div></div></div></div>`;
 const worlds=projectWorlds(),side=content.querySelector('.road-summary');side.insertAdjacentHTML('beforeend',`<div class="panel worlds-panel"><div class="panel-head"><h2>Światy projektu</h2><button id="add-world-button" class="mini-button" type="button">＋</button></div>${worlds.length?`<div class="world-chip-list">${worlds.map(world=>`<span><b>${escapeHtml(worldLabel(world))}</b>${world.description?`<small>${escapeHtml(world.description)}</small>`:''}</span>`).join('')}</div>`:'<p class="panel-note">Dodaj światy, aby przypisywać do nich wydarzenia i budować spotkania.</p>'}</div>`);
 if(focusedCharacter){content.querySelector('.road-top').insertAdjacentHTML('afterend',`<div class="character-focus-banner"><span>♙</span><div><small>DROGA POSTACI</small><b>${escapeHtml(focusedCharacter.name)}</b><em>${events.length} wydarzeń · ${sources.length} źródeł</em></div><button id="clear-character-focus" type="button">Pokaż całą kronikę ×</button></div>`);$('#clear-character-focus').onclick=()=>{selectedCharacterId=null;renderRoad()}}
 $$('.road-modes button').forEach(mode=>mode.addEventListener('click',()=>{roadMode=mode.dataset.roadMode;renderRoad()}));
 $('#road-add-item')?.addEventListener('click',roadMode==='events'?openEventDialog:openSourceDialog);
 $('#add-world-button')?.addEventListener('click',()=>openWorldDialog());
 $('#export-project')?.addEventListener('click',exportProject);
 $('#import-project')?.addEventListener('click',()=>$('#import-project-file').click());
 $('#import-project-file')?.addEventListener('change',event=>{importProjectFile(event.target.files[0]);event.target.value=''})
}
function bindProjectEmpty(id){$('#'+id)?.addEventListener('click',()=>openDialog('#project-dialog'))}
function renderSources(){const project=activeProject(),content=$('#sources-content');if(!project){content.innerHTML=empty('▤','Najpierw utwórz projekt','Każde źródło należy do konkretnej drogi.','Utwórz projekt','sources-new-project');bindProjectEmpty('sources-new-project');return}const sources=project.sources||[],filtered=filteredSources().slice().sort(chronologicalCompare),visible=filtered.slice(0,sourceVisibleLimit);content.innerHTML=sources.length?`${sourceControls()}<div class="panel"><div class="panel-head"><h2>Materiały według daty akcji</h2><span class="counter">${filtered.length} / ${sources.length}</span></div>${visible.length?`<div class="list">${visible.map(sourceRow).join('')}</div>`:'<p class="panel-note">Żadne źródło nie ma wybranego hashtagu.</p>'}${visible.length<filtered.length?`<button id="show-more-sources" class="secondary-button show-more-sources" type="button">Pokaż kolejne ${Math.min(160,filtered.length-visible.length)}</button>`:''}</div>`:empty('▤','Brak źródeł','Dodaj pierwszy materiał bez gotowych przykładów i sztucznego wypełniania.','Dodaj źródło','sources-add-first');bindSourceControls(content);$('#show-more-sources')?.addEventListener('click',()=>{sourceVisibleLimit+=160;renderSources()});$('#sources-add-first')?.addEventListener('click',openSourceDialog)}
function timeLabel(type){return({exact:'dokładnie',approx:'około',before:'przed',after:'po',parallel:'równolegle',order:'kolejność',unknown:'nieustalone'})[type]||'nieustalone'}
function eventRow(event){const project=activeProject(),sources=eventSources(event),primary=sources.find(source=>source.id===event.sourceId)||sources[0],characters=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)),related=(project.events||[]).find(item=>item.id===event.relationEventId),relation=related?`<small class="event-relation">↳ ${timeLabel(event.timeType)}: ${escapeHtml(related.title)}</small>`:'',effectiveDate=event.date||sources.map(source=>source.date).filter(Boolean).sort()[0],worldLinks=(event.worldLinks||[]).filter(name=>name&&name!==event.world),meeting=worldLinks.length?`<span class="tag convergence-tag">spotkanie: ${escapeHtml(worldLinks.join(' + '))}</span>`:'',sourceNames=sources.map(source=>source.title).join(' · ');return `<article class="list-item"><span class="list-mark">●</span><div class="list-copy"><b>${escapeHtml(event.title)}</b><small>${escapeHtml(sourceNames||'Bez przypisanego źródła')} · ${dateLabel(effectiveDate,event.date?event.timeType==='approx':primary?.dateApprox)}</small>${relation}<div class="tag-row">${event.world?`<span class="tag">${escapeHtml(event.world)}</span>`:''}${meeting}${event.place?`<span class="tag">${escapeHtml(event.place)}</span>`:''}${characters.map(character=>`<span class="tag character-tag">♙ ${escapeHtml(character.name)}</span>`).join('')}${event.inbox?'<span class="tag inbox-tag">do uporządkowania</span>':''}</div></div><span class="status">${timeLabel(event.timeType)}</span>${itemActions('event',event.id)}</article>`}
function renderEvents(){const project=activeProject(),content=$('#events-content');if(!project){content.innerHTML=empty('●','Najpierw utwórz projekt','Wydarzenia będą zapisywane wewnątrz wybranej kroniki.','Utwórz projekt','events-new-project');bindProjectEmpty('events-new-project');return}const events=(project.events||[]).slice().reverse();content.innerHTML=events.length?`<div class="panel"><div class="panel-head"><h2>Dziennik wydarzeń</h2><span class="counter">${events.length}</span></div><div class="list">${events.map(eventRow).join('')}</div></div>`:empty('●','Dziennik jest pusty','Jedno zdanie wystarczy. Świat, miejsce i chronologię możesz dopisać później.','Dodaj wydarzenie','events-add-first');$('#events-add-first')?.addEventListener('click',openEventDialog)}
function characterConnections(characterId){const project=activeProject(),events=(project?.events||[]).filter(event=>(event.characterIds||[]).includes(characterId)),ids=new Set(events.flatMap(event=>event.characterIds||[]).filter(id=>id!==characterId));return{events,characters:projectCharacters().filter(character=>ids.has(character.id))}}
function characterRow(character){const links=characterConnections(character.id),aliases=characterAliases(character),life=[character.birthDate||'?',character.deathDate||'…'].join(' – ');return `<article class="list-item character-item"><span class="list-mark">♙</span><div class="list-copy"><b>${escapeHtml(character.name)}</b><small>${escapeHtml(aliases.join(' / ')||'Bez alternatywnych imion')} · ${escapeHtml(character.world||'świat nieustalony')} · ${escapeHtml(life)}</small><div class="tag-row">${links.characters.slice(0,6).map(item=>`<span class="tag connection-tag">↔ ${escapeHtml(item.name)}</span>`).join('')}</div></div><span class="status">${links.characters.length} koneksji</span><button class="focus-character mini-button" data-character-focus="${character.id}" type="button" title="Pokaż chronologiczną drogę postaci">⌁</button>${itemActions('character',character.id)}</article>`}
function renderCharacters(){const project=activeProject(),content=$('#characters-content');if(!project){content.innerHTML=empty('♙','Najpierw utwórz projekt','Postacie będą należały do wybranej kroniki.','Utwórz projekt','characters-new-project');bindProjectEmpty('characters-new-project');return}const characters=projectCharacters();content.innerHTML=characters.length?`<div class="panel"><div class="panel-head"><h2>Kartoteka postaci</h2><span class="counter">${characters.length}</span></div><div class="list">${characters.map(characterRow).join('')}</div></div>`:empty('♙','Brak postaci','Dodaj postać, a następnie przypisuj ją bezpośrednio do wydarzeń.','Dodaj postać','characters-add-first');$('#characters-add-first')?.addEventListener('click',()=>openCharacterDialog())}
function renderAtlas(){const project=activeProject(),events=project?.events||[],worlds=project?projectWorlds():[],connections=events.flatMap(event=>(event.worldLinks||[]).filter(name=>name&&name!==event.world).map(name=>({from:event.world||'Świat nieustalony',to:name,event:event.title})));if(!project||!worlds.length){$('#atlas-content').innerHTML=`<div class="atlas-placeholder"><div class="atlas-grid"></div><div class="atlas-message"><div><div class="empty-icon">⌖</div><h2>${project?'Atlas czeka na światy':'Najpierw utwórz projekt'}</h2><p>${project?'Dodaj pierwszy świat w widoku Road. Każdy pozostanie osobnym węzłem, nawet gdy później spotka się z innym.':'Atlas należy do wybranego projektu i pozostaje całkowicie pusty.'}</p></div></div></div>`;return}$('#atlas-content').innerHTML=`<div class="world-network"><div class="panel-head"><h2>Wszystkie połączone światy</h2><span class="counter">${worlds.length}</span></div><div class="world-nodes">${worlds.map((world,index)=>`<article class="world-node" style="--world-index:${index}"><span>◉</span><b>${escapeHtml(worldLabel(world))}</b><small>${escapeHtml(world.description||'Osobna gałąź projektu')}</small></article>`).join('')}</div><div class="world-bridges">${connections.length?connections.map(link=>`<article><span>${escapeHtml(link.from)}</span><i>→</i><span>${escapeHtml(link.to)}</span><b>${escapeHtml(link.event)}</b></article>`).join(''):'<p class="panel-note">Światy są jeszcze rozdzielone. Spotkanie zapisane w wydarzeniu utworzy tutaj most.</p>'}</div></div>`}
function updateActions(){const hasProject=Boolean(activeProject());$('#quick-event-button').disabled=!hasProject;$('#add-source-button').disabled=!hasProject;$('#add-character-button').disabled=!hasProject;$('#add-event-button').disabled=!hasProject;$('#import-extended-vo').disabled=!hasProject;$('#import-multiversal-vo').disabled=!hasProject}
function render(){renderProjectSelect();renderRoad();renderSources();renderCharacters();renderEvents();renderAtlas();updateActions()}
function switchView(view){$$('.view').forEach(section=>section.classList.toggle('active',section.id==='view-'+view));$$('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
function ensureCharacterDialog(){if($('#character-dialog'))return;const dialog=document.createElement('dialog');dialog.id='character-dialog';dialog.className='dialog';dialog.innerHTML='<form id="character-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">POSTAĆ</p><h2>Dodaj postać</h2><label>Nazwa<input id="character-name" required autocomplete="off"></label><label>Alter ego i alternatywne imiona<input id="character-aliases" autocomplete="off" placeholder="Np. Logan, James Howlett, Weapon X"><small>Możesz podać kilka nazw oddzielonych przecinkami.</small></label><label>Świat pochodzenia<div class="inline-field"><input id="character-world" list="project-world-list" autocomplete="off"><button id="add-character-world" class="mini-button" type="button" title="Dodaj nowy świat">＋</button></div></label><div class="form-row"><label>Data urodzenia<input id="character-birth" type="date"></label><label>Data śmierci<input id="character-death" type="date"></label></div><button class="primary-button full" value="save" type="submit">Dodaj postać</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>{characterDialogTarget=null;dialog.close()};dialog.querySelector('#add-character-world').onclick=()=>openWorldDialog('character');dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const name=$('#character-name').value.trim();if(!name)return;const data={name,aliases:$('#character-aliases').value.split(',').map(alias=>alias.trim()).filter(Boolean),world:$('#character-world').value.trim(),birthDate:$('#character-birth').value,deathDate:$('#character-death').value};let characterId=editingCharacterId;if(editingCharacterId){const item=projectCharacters().find(character=>character.id===editingCharacterId);if(item){delete item.alterEgo;Object.assign(item,data)}}else{characterId=uid('character');projectCharacters().push({id:characterId,...data})}const target=characterDialogTarget;editingCharacterId=null;characterDialogTarget=null;save();dialog.close();render();if(target==='event'){ensureCharacterFields();const input=$(`#event-characters input[value="${characterId}"]`);if(input)input.checked=true}})}
function openCharacterDialog(characterId=null,target=null){if(!activeProject())return openDialog('#project-dialog');ensureWorldFields();ensureCharacterDialog();editingCharacterId=characterId;characterDialogTarget=target;$('#character-form').reset();const item=projectCharacters().find(character=>character.id===characterId);if(item){$('#character-name').value=item.name;$('#character-aliases').value=characterAliases(item).join(', ');$('#character-world').value=item.world||'';$('#character-birth').value=item.birthDate||'';$('#character-death').value=item.deathDate||'';$('#character-dialog h2').textContent='Edytuj postać';$('#character-form .primary-button').textContent='Zapisz zmiany'}else{$('#character-dialog h2').textContent='Dodaj postać';$('#character-form .primary-button').textContent='Dodaj postać'}openDialog('#character-dialog')}
function ensureWorldDialog(){if($('#world-dialog'))return;const dialog=document.createElement('dialog');dialog.id='world-dialog';dialog.className='dialog';dialog.innerHTML='<form id="world-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">NOWY ŚWIAT</p><h2>Dodaj świat do projektu</h2><label>Numer, nazwa lub oznaczenie<input id="world-designation" required autocomplete="off" placeholder="Np. Earth-616 albo TRN414"></label><label>Krótki opis<input id="world-description" required autocomplete="off" placeholder="Np. MCU, główne komiksy Marvela, X-Men Foxa"></label><button class="primary-button full" value="save" type="submit">Dodaj świat</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>{worldDialogTarget=null;dialog.close()};dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const designation=$('#world-designation').value.trim(),description=$('#world-description').value.trim();if(!designation||!description||projectWorlds().some(world=>worldLabel(world).toLowerCase()===designation.toLowerCase()))return;const world={id:uid('world'),designation,name:designation,description};projectWorlds().push(world);const target=worldDialogTarget;worldDialogTarget=null;save();dialog.close();render();if(target==='event')$('#event-world').value=designation;if(target==='character')$('#character-world').value=designation;if(target==='source'){ensureSourceWorldFields([world.id]);const input=$(`#source-worlds input[value="${world.id}"]`);if(input)input.checked=true}})}
function openWorldDialog(target=null){if(!activeProject())return openDialog('#project-dialog');worldDialogTarget=target;ensureWorldDialog();$('#world-form').reset();openDialog('#world-dialog')}
function ensureWorldFields(){ensureDateFields();let list=$('#project-world-list');if(!list){list=document.createElement('datalist');list.id='project-world-list';document.body.append(list);$('#event-world').setAttribute('list','project-world-list')}list.innerHTML=projectWorlds().map(world=>`<option value="${escapeHtml(worldLabel(world))}">${escapeHtml(world.description||'')}</option>`).join('');if(!$('#add-event-world')){const input=$('#event-world'),wrap=document.createElement('div'),button=document.createElement('button');wrap.className='inline-field';button.id='add-event-world';button.className='mini-button';button.type='button';button.title='Dodaj nowy świat';button.textContent='＋';input.before(wrap);wrap.append(input,button);button.addEventListener('click',()=>openWorldDialog('event'))}let links=$('#event-world-links');if(!links){links=document.createElement('fieldset');links.id='event-world-links';links.className='world-links';$('#event-world').closest('.form-row').after(links)}links.innerHTML='<legend>Światy uczestniczące w spotkaniu</legend><p>Zaznacz dodatkowe światy, których linie łączą się w tym wydarzeniu.</p><div>'+projectWorlds().map(world=>`<label><input type="checkbox" value="${escapeHtml(worldLabel(world))}"> ${escapeHtml(worldLabel(world))} · ${escapeHtml(world.description||'')}</label>`).join('')+'</div>';ensureCharacterFields()}
function ensureCharacterFields(){let field=$('#event-characters'),selected=new Set(field?[...field.querySelectorAll('input:checked')].map(input=>input.value):[]);if(!field){field=document.createElement('fieldset');field.id='event-characters';field.className='event-characters';const anchor=$('#event-extra-sources')||$('#event-source')?.closest('.form-row');if(!anchor)return;anchor.after(field)}const item=activeProject()?.events.find(event=>event.id===editingEventId);if(item)(item.characterIds||[]).forEach(id=>selected.add(id));field.innerHTML='<legend>Postacie uczestniczące w wydarzeniu <button id="add-event-character" class="mini-button" type="button" title="Dodaj nową postać">＋</button></legend><div>'+projectCharacters().map(character=>`<label><input type="checkbox" value="${character.id}"> ${escapeHtml(character.name)}${characterAliases(character).length?' / '+escapeHtml(characterAliases(character).join(' / ')):''}</label>`).join('')+'</div>';field.querySelectorAll('input').forEach(input=>input.checked=selected.has(input.value));$('#add-event-character').onclick=()=>openCharacterDialog(null,'event')}
function ensureDateFields(){if(!$('#source-date-row')){const row=document.createElement('div');row.id='source-date-row';row.className='form-row';row.innerHTML='<label>Data akcji źródła<input id="source-date" type="text" autocomplete="off" placeholder="Np. 1260 BC, 10 AD, 2026-09-28"></label><label class="check date-check"><input id="source-date-approx" type="checkbox"> Data przybliżona</label>';$('#source-status').closest('.form-row').after(row);const releaseRow=document.createElement('div');releaseRow.id='source-release-row';releaseRow.className='form-row';releaseRow.innerHTML='<label>Data premiery / wydania<input id="source-release-date" type="date" autocomplete="off"></label><label><span>Porządek publikacji</span><small>Osobna od daty akcji. Posłuży do widoku kolejności premier.</small></label>';row.after(releaseRow)}if(!$('#event-date-row')){const row=document.createElement('div');row.id='event-date-row';row.className='form-row event-date-row';row.hidden=true;row.innerHTML='<label>Data opisowa wydarzenia<input id="event-date" type="text" autocomplete="off" placeholder="Np. początek czasu, 1260 BC, 10 AD"></label><label><span>Dziedziczenie daty</span><small>Jeśli pole zostanie puste, wydarzenie użyje daty akcji źródła.</small></label>';$('#event-time-type').closest('.form-row').after(row)}}
function ensureSourceWorldFields(selectedIds=[]){let field=$('#source-worlds'),selected=new Set(selectedIds);if(field)field.querySelectorAll('input:checked').forEach(input=>selected.add(input.value));if(!field){field=document.createElement('fieldset');field.id='source-worlds';field.className='world-links';$('#source-release-row').after(field)}field.innerHTML='<legend>Światy źródła <button id="add-source-world" class="mini-button" type="button" title="Dodaj nowy świat">＋</button></legend><p>Opcjonalnie przypisz jeden lub kilka światów występujących w tym źródle.</p><div>'+projectWorlds().map(world=>`<label><input type="checkbox" value="${world.id}"> ${escapeHtml(worldLabel(world))} · ${escapeHtml(world.description||'')}</label>`).join('')+'</div>';field.querySelectorAll('input').forEach(input=>input.checked=selected.has(input.value));$('#add-source-world').onclick=()=>openWorldDialog('source')}
function renderEventDateField(){const row=$('#event-date-row');if(row)row.hidden=!['exact','approx'].includes($('#event-time-type').value)}
function openSourceDialog(sourceId=null,target=null){if(!activeProject())return openDialog('#project-dialog');editingSourceId=sourceId;sourceDialogTarget=target;ensureDateFields();$('#source-form').reset();let selected=[];if(sourceId){const item=activeProject().sources.find(source=>source.id===sourceId);if(item){selected=item.worldIds||[];$('#source-title').value=item.title;$('#source-type').value=item.type;$('#source-status').value=item.status;$('#source-date').value=item.date||'';$('#source-date-approx').checked=Boolean(item.dateApprox);$('#source-release-date').value=item.releaseDate||'';$('#source-dialog h2').textContent='Edytuj źródło';$('#source-form .primary-button').textContent='Zapisz zmiany'}}else{$('#source-dialog h2').textContent='Dodaj materiał';$('#source-form .primary-button').textContent='Dodaj do Road'}ensureSourceWorldFields(selected);openDialog('#source-dialog')}
function populateEventSources(){const select=$('#event-source'),sources=activeProject()?.sources||[],selected=select.value,checked=new Set($('#event-extra-sources')?[...$('#event-extra-sources').querySelectorAll('input:checked')].map(input=>input.value):[]);select.previousSibling&&(select.closest('label').childNodes[0].textContent='Źródło główne');select.innerHTML='<option value="">Bez źródła głównego</option>';sources.forEach(source=>{const option=document.createElement('option');option.value=source.id;option.textContent=source.title;select.append(option)});select.value=selected;let extra=$('#event-extra-sources');if(!extra){extra=document.createElement('fieldset');extra.id='event-extra-sources';extra.className='extra-sources';select.closest('.form-row').after(extra)}extra.innerHTML='<legend>Dodatkowe źródła tego samego wydarzenia <button id="add-event-source" class="mini-button" type="button" title="Dodaj nowe źródło">＋</button></legend><div>'+sources.map(source=>`<label><input type="checkbox" value="${source.id}"> ${escapeHtml(source.title)}</label>`).join('')+'</div>';extra.querySelectorAll('input').forEach(input=>input.checked=checked.has(input.value));$('#add-event-source').onclick=()=>openSourceDialog(null,'event')}
function ensureRelationPicker(){if($('#event-relation-picker'))return;const panel=document.createElement('section');panel.id='event-relation-picker';panel.className='relation-picker';panel.hidden=true;panel.innerHTML='<div class="relation-head"><div><b>Wybierz powiązane wydarzenie</b><small>Wyszukaj nazwę, postać, tag, świat lub miejsce</small></div><span id="relation-count"></span></div><input id="event-relation-search" type="search" autocomplete="off" placeholder="Szukaj wydarzenia lub osoby…"><div id="event-relation-results" class="relation-results"></div><p id="event-relation-error" class="relation-error" hidden>Wybierz wydarzenie, z którym tworzysz relację.</p>';const anchor=$('#event-world').closest('.form-row');anchor.before(panel);$('#event-relation-search').addEventListener('input',renderRelationPicker)}
function relationHaystack(event){const names=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)).flatMap(character=>[character.name,...characterAliases(character)]);return [event.title,event.world,event.place,event.notes,...eventSources(event).map(source=>source.title),...names,...(event.tags||[])].filter(Boolean).join(' ').toLowerCase()}
function renderRelationPicker(){const panel=$('#event-relation-picker');if(!panel)return;const type=$('#event-time-type').value,visible=RELATION_TYPES.has(type);panel.hidden=!visible;if(!visible){selectedRelationId=null;return}const project=activeProject(),query=$('#event-relation-search').value.trim().toLowerCase(),events=(project?.events||[]).filter(event=>!query||relationHaystack(event).includes(query)),sources=project?.sources||[],groups=new Map();events.forEach(event=>{const key=event.sourceId||'';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(event)});$('#relation-count').textContent=events.length+' wyników';const results=$('#event-relation-results');if(!events.length){results.innerHTML='<div class="relation-empty">Nie znaleziono pasującego wydarzenia.</div>';return}const ordered=[...sources.map(source=>source.id),''].filter((id,index,array)=>groups.has(id)&&array.indexOf(id)===index);results.innerHTML=ordered.map(sourceId=>{const source=sources.find(item=>item.id===sourceId),items=groups.get(sourceId)||[];return `<div class="relation-group"><p>${escapeHtml(source?.title||'Bez przypisanego źródła')}</p>${items.map(event=>`<button class="relation-option${event.id===selectedRelationId?' selected':''}" type="button" data-event-id="${event.id}"><b>${escapeHtml(event.title)}</b><small>${escapeHtml([...(event.tags||[]),event.world,event.place].filter(Boolean).join(' · ')||'Bez dodatkowych tagów')}</small></button>`).join('')}</div>`}).join('');results.querySelectorAll('.relation-option').forEach(button=>button.addEventListener('click',()=>{selectedRelationId=button.dataset.eventId;$('#event-relation-error').hidden=true;renderRelationPicker()}))}
function openEventDialog(eventId=null){if(!activeProject())return openDialog('#project-dialog');editingEventId=eventId;ensureWorldFields();$('#event-form').reset();$('#event-inbox').checked=true;selectedRelationId=null;populateEventSources();ensureCharacterFields();ensureRelationPicker();$('#event-relation-search').value='';if(eventId){const item=activeProject().events.find(event=>event.id===eventId);if(item){$('#event-title').value=item.title;$('#event-source').value=item.sourceId||'';$('#event-time-type').value=item.timeType||'unknown';$('#event-date').value=item.date||'';$('#event-world').value=item.world||'';$('#event-place').value=item.place||'';$('#event-tags').value=(item.tags||[]).join(', ');$('#event-notes').value=item.notes||'';$('#event-inbox').checked=Boolean(item.inbox);selectedRelationId=item.relationEventId||null;$('#event-dialog h2').textContent='Edytuj wydarzenie';$('#event-form .primary-button').textContent='Zapisz zmiany';$('#event-extra-sources').querySelectorAll('input').forEach(input=>input.checked=eventSourceIds(item).includes(input.value)&&input.value!==item.sourceId);$('#event-world-links').querySelectorAll('input').forEach(input=>input.checked=(item.worldLinks||[]).includes(input.value));$('#event-characters').querySelectorAll('input').forEach(input=>input.checked=(item.characterIds||[]).includes(input.value))}}else{$('#event-dialog h2').textContent='Co się wydarzyło?';$('#event-form .primary-button').textContent='Zapisz i dodaj następne'}renderEventDateField();renderRelationPicker();openDialog('#event-dialog')}

$$('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$$('.dialog-close').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close()}));
$('#brand-home').addEventListener('click',()=>switchView('road'));
$('#theme-button').addEventListener('click',openThemeDialog);
$('#new-project-main').addEventListener('click',()=>activeProject()?openSourceDialog():openDialog('#project-dialog'));
$('#new-project-side').addEventListener('click',()=>openDialog('#project-dialog'));
$('#quick-event-button').addEventListener('click',openEventDialog);$('#add-event-button').addEventListener('click',openEventDialog);$('#add-source-button').addEventListener('click',openSourceDialog);$('#add-character-button').addEventListener('click',()=>openCharacterDialog());
$('#import-extended-vo').addEventListener('click',importExtendedVo);
$('#import-multiversal-vo').addEventListener('click',importMultiversalVo);
$('#event-time-type').addEventListener('change',()=>{ensureDateFields();ensureRelationPicker();renderEventDateField();renderRelationPicker()});
$('#project-select').addEventListener('change',event=>{state.activeProjectId=event.target.value||null;save();render()});
$('.main').addEventListener('click',event=>{const button=event.target.closest('button[data-id]');if(!button)return;const project=activeProject(),id=button.dataset.id;if(button.classList.contains('edit-source'))openSourceDialog(id);if(button.classList.contains('edit-event'))openEventDialog(id);if(button.classList.contains('edit-character'))openCharacterDialog(id);if(button.classList.contains('delete-source')&&confirm('Usunąć to źródło? Powiązane wydarzenia pozostaną w projekcie.')){project.sources=project.sources.filter(source=>source.id!==id);project.events.forEach(item=>{if(item.sourceId===id)item.sourceId=null;item.sourceIds=eventSourceIds(item).filter(sourceId=>sourceId!==id)});save();render()}if(button.classList.contains('delete-event')&&confirm('Usunąć to wydarzenie?')){project.events=project.events.filter(item=>item.id!==id);project.events.forEach(item=>{if(item.relationEventId===id)item.relationEventId=null});save();render()}if(button.classList.contains('delete-character')&&confirm('Usunąć tę postać? Zniknie także z przypisanych wydarzeń.')){project.characters=projectCharacters().filter(character=>character.id!==id);project.events.forEach(item=>item.characterIds=(item.characterIds||[]).filter(characterId=>characterId!==id));save();render()}});
$('#project-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const name=$('#project-name').value.trim();if(!name)return;const project={id:uid('project'),name,description:$('#project-description').value.trim(),createdAt:new Date().toISOString(),worlds:[],sources:[],characters:[],events:[]};state.projects.push(project);state.activeProjectId=project.id;save();event.currentTarget.reset();$('#project-dialog').close();render();switchView('road')});
$('#source-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#source-title').value.trim();if(!project||!title)return;const data={title,type:$('#source-type').value,status:$('#source-status').value,date:$('#source-date')?.value||'',dateApprox:$('#source-date-approx')?.checked||false,releaseDate:$('#source-release-date')?.value||'',worldIds:[...$('#source-worlds').querySelectorAll('input:checked')].map(input=>input.value)};let sourceId=editingSourceId;if(editingSourceId){const item=project.sources.find(source=>source.id===editingSourceId);if(item)Object.assign(item,data)}else{sourceId=uid('source');project.sources.push({id:sourceId,...data,createdAt:new Date().toISOString()})}const target=sourceDialogTarget;editingSourceId=null;sourceDialogTarget=null;save();event.currentTarget.reset();$('#source-dialog').close();render();if(target==='event'){populateEventSources();$('#event-source').value=sourceId;ensureCharacterFields()}else switchView('road')});
$('#event-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#event-title').value.trim(),timeType=$('#event-time-type').value;if(!project||!title)return;if(RELATION_TYPES.has(timeType)&&!selectedRelationId){$('#event-relation-error').hidden=false;$('#event-relation-picker').scrollIntoView({block:'nearest'});return}const sourceId=$('#event-source').value||null,extraSources=[...$('#event-extra-sources').querySelectorAll('input:checked')].map(input=>input.value).filter(id=>id!==sourceId),data={title,sourceId,sourceIds:[sourceId,...extraSources].filter(Boolean),characterIds:[...$('#event-characters').querySelectorAll('input:checked')].map(input=>input.value),timeType,date:$('#event-date')?.value||'',relationEventId:selectedRelationId,world:$('#event-world').value.trim(),worldLinks:[...$('#event-world-links').querySelectorAll('input:checked')].map(input=>input.value),place:$('#event-place').value.trim(),tags:$('#event-tags').value.split(',').map(tag=>tag.trim()).filter(Boolean),notes:$('#event-notes').value.trim(),inbox:$('#event-inbox').checked};if(editingEventId){const item=project.events.find(existing=>existing.id===editingEventId);if(item)Object.assign(item,data);editingEventId=null;save();$('#event-dialog').close();render();return}project.events.push({id:uid('event'),...data,createdAt:new Date().toISOString()});save();event.currentTarget.reset();selectedRelationId=null;populateEventSources();ensureCharacterFields();$('#event-source').value=sourceId||'';$('#event-inbox').checked=true;renderEventDateField();renderRelationPicker();render();$('#event-title').focus()});

$('.main').addEventListener('click',event=>{const button=event.target.closest('[data-character-focus]');if(!button)return;selectedCharacterId=button.dataset.characterFocus;roadMode='events';renderRoad();switchView('road')});
migrateLegacySourceTags();applyTheme();render();switchView('road');void enrichSourceMetadata();
