const STORAGE_KEY='chronizo.workbench.v1';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const freshState=()=>({projects:[],activeProjectId:null});
let state=load();

function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return parsed&&Array.isArray(parsed.projects)?parsed:freshState()}catch{return freshState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function activeProject(){return state.projects.find(project=>project.id===state.activeProjectId)||null}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function openDialog(selector){const dialog=$(selector);dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type="checkbox"]),textarea,select')?.focus())}
function empty(icon,title,copy,action='',buttonId=''){return `<div class="empty-state"><div class="empty-state-inner"><div class="empty-icon">${icon}</div><h2>${title}</h2><p>${copy}</p>${action?`<button id="${buttonId}" class="primary-button" type="button">${action}</button>`:''}</div></div>`}

function renderProjectSelect(){const select=$('#project-select');select.innerHTML='';if(!state.projects.length){const option=document.createElement('option');option.textContent='Brak projektu';option.value='';select.append(option);select.disabled=true;return}select.disabled=false;state.projects.forEach(project=>{const option=document.createElement('option');option.value=project.id;option.textContent=project.name;option.selected=project.id===state.activeProjectId;select.append(option)})}
function sourceRow(source){return `<article class="list-item"><span class="list-mark">▤</span><div class="list-copy"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)}</small></div><span class="status">${escapeHtml(source.status)}</span></article>`}
function renderRoad(){
 const project=activeProject(),content=$('#road-content'),button=$('#new-project-main');
 if(!project){$('#road-title').textContent='Zacznij własną kronikę';$('#road-subtitle').textContent='Bez przykładów. Bez narzuconego uniwersum. To miejsce czeka na Twoją historię.';button.textContent='Utwórz pierwszy projekt';content.innerHTML=empty('◫','Tabula rasa','Utwórz projekt, nadaj mu własną nazwę i zacznij dodawać materiały. Chronizo nie wstawia żadnych przykładowych światów, postaci ani wydarzeń.','Utwórz projekt','empty-new-project');$('#empty-new-project').onclick=()=>openDialog('#project-dialog');return}
 const sources=project.sources||[],events=project.events||[],inbox=events.filter(event=>event.inbox),recent=sources.slice(-6).reverse();
 $('#road-title').textContent=project.name;$('#road-subtitle').textContent=project.description||'Twoja droga przez źródła i wydarzenia.';button.textContent='＋ Dodaj źródło';
 content.innerHTML=`<div class="dashboard-grid"><div class="panel"><div class="panel-head"><h2>Road</h2><span class="counter">${sources.length} źródeł</span></div>${recent.length?`<div class="list">${recent.map(sourceRow).join('')}</div>`:empty('▤','Droga jest jeszcze pusta','Dodaj pierwszy film, serial, komiks albo inne źródło.','Dodaj źródło','road-add-source')}</div><div><div class="panel"><div class="panel-head"><h2>Stan kroniki</h2></div><div class="metric-grid"><div class="metric"><strong>${sources.length}</strong><span>źródła</span></div><div class="metric"><strong>${events.length}</strong><span>wydarzenia</span></div><div class="metric"><strong>${inbox.length}</strong><span>do uporządkowania</span></div></div></div></div></div>`;
 $('#road-add-source')?.addEventListener('click',openSourceDialog);
}
function bindProjectEmpty(id){$('#'+id)?.addEventListener('click',()=>openDialog('#project-dialog'))}
function renderSources(){const project=activeProject(),content=$('#sources-content');if(!project){content.innerHTML=empty('▤','Najpierw utwórz projekt','Każde źródło należy do konkretnej drogi.','Utwórz projekt','sources-new-project');bindProjectEmpty('sources-new-project');return}const sources=project.sources||[];content.innerHTML=sources.length?`<div class="panel"><div class="panel-head"><h2>Materiały</h2><span class="counter">${sources.length}</span></div><div class="list">${sources.map(sourceRow).join('')}</div></div>`:empty('▤','Brak źródeł','Dodaj pierwszy materiał bez gotowych przykładów i sztucznego wypełniania.','Dodaj źródło','sources-add-first');$('#sources-add-first')?.addEventListener('click',openSourceDialog)}
function timeLabel(type){return({exact:'dokładnie',approx:'około',before:'przed',after:'po',parallel:'równolegle',order:'kolejność',unknown:'nieustalone'})[type]||'nieustalone'}
function eventRow(event){const project=activeProject(),source=(project.sources||[]).find(item=>item.id===event.sourceId);return `<article class="list-item"><span class="list-mark">●</span><div class="list-copy"><b>${escapeHtml(event.title)}</b><small>${source?escapeHtml(source.title):'Bez przypisanego źródła'}</small><div class="tag-row">${event.world?`<span class="tag">${escapeHtml(event.world)}</span>`:''}${event.place?`<span class="tag">${escapeHtml(event.place)}</span>`:''}${event.inbox?'<span class="tag inbox-tag">do uporządkowania</span>':''}</div></div><span class="status">${timeLabel(event.timeType)}</span></article>`}
function renderEvents(){const project=activeProject(),content=$('#events-content');if(!project){content.innerHTML=empty('●','Najpierw utwórz projekt','Wydarzenia będą zapisywane wewnątrz wybranej kroniki.','Utwórz projekt','events-new-project');bindProjectEmpty('events-new-project');return}const events=(project.events||[]).slice().reverse();content.innerHTML=events.length?`<div class="panel"><div class="panel-head"><h2>Dziennik wydarzeń</h2><span class="counter">${events.length}</span></div><div class="list">${events.map(eventRow).join('')}</div></div>`:empty('●','Dziennik jest pusty','Jedno zdanie wystarczy. Świat, miejsce i chronologię możesz dopisać później.','Dodaj wydarzenie','events-add-first');$('#events-add-first')?.addEventListener('click',openEventDialog)}
function renderAtlas(){const project=activeProject(),events=project?.events||[];$('#atlas-content').innerHTML=`<div class="atlas-placeholder"><div class="atlas-grid"></div><div class="atlas-message"><div><div class="empty-icon">⌖</div><h2>${project?'Atlas czeka na dane':'Najpierw utwórz projekt'}</h2><p>${project?(events.length?'Masz już '+events.length+' wydarzeń. W kolejnych etapach Chronizo zbuduje z nich chronologię, linie postaci i mapę miejsc.':'Kiedy zapiszesz wydarzenia, tutaj powstanie ich wizualna mapa. Atlas nie dodaje żadnych miejsc ani światów samodzielnie.'):'Atlas należy do wybranego projektu i pozostaje całkowicie pusty.'}</p></div></div></div>`}
function updateActions(){const hasProject=Boolean(activeProject());$('#quick-event-button').disabled=!hasProject;$('#add-source-button').disabled=!hasProject;$('#add-event-button').disabled=!hasProject}
function render(){renderProjectSelect();renderRoad();renderSources();renderEvents();renderAtlas();updateActions()}
function switchView(view){$$('.view').forEach(section=>section.classList.toggle('active',section.id==='view-'+view));$$('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
function openSourceDialog(){if(!activeProject())return openDialog('#project-dialog');$('#source-form').reset();openDialog('#source-dialog')}
function populateEventSources(){const select=$('#event-source'),sources=activeProject()?.sources||[];select.innerHTML='<option value="">Bez przypisanego źródła</option>';sources.forEach(source=>{const option=document.createElement('option');option.value=source.id;option.textContent=source.title;select.append(option)})}
function openEventDialog(){if(!activeProject())return openDialog('#project-dialog');$('#event-form').reset();$('#event-inbox').checked=true;populateEventSources();openDialog('#event-dialog')}

$$('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$$('.dialog-close').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close()}));
$('#brand-home').addEventListener('click',()=>switchView('road'));
$('#theme-button').addEventListener('click',()=>document.body.classList.toggle('light'));
$('#new-project-main').addEventListener('click',()=>activeProject()?openSourceDialog():openDialog('#project-dialog'));
$('#new-project-side').addEventListener('click',()=>openDialog('#project-dialog'));
$('#quick-event-button').addEventListener('click',openEventDialog);$('#add-event-button').addEventListener('click',openEventDialog);$('#add-source-button').addEventListener('click',openSourceDialog);
$('#project-select').addEventListener('change',event=>{state.activeProjectId=event.target.value||null;save();render()});
$('#project-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const name=$('#project-name').value.trim();if(!name)return;const project={id:uid('project'),name,description:$('#project-description').value.trim(),createdAt:new Date().toISOString(),sources:[],events:[]};state.projects.push(project);state.activeProjectId=project.id;save();event.currentTarget.reset();$('#project-dialog').close();render();switchView('road')});
$('#source-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#source-title').value.trim();if(!project||!title)return;project.sources.push({id:uid('source'),title,type:$('#source-type').value,status:$('#source-status').value,createdAt:new Date().toISOString()});save();event.currentTarget.reset();$('#source-dialog').close();render();switchView('road')});
$('#event-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#event-title').value.trim();if(!project||!title)return;project.events.push({id:uid('event'),title,sourceId:$('#event-source').value||null,timeType:$('#event-time-type').value,world:$('#event-world').value.trim(),place:$('#event-place').value.trim(),tags:$('#event-tags').value.split(',').map(tag=>tag.trim()).filter(Boolean),notes:$('#event-notes').value.trim(),inbox:$('#event-inbox').checked,createdAt:new Date().toISOString()});save();const sourceId=$('#event-source').value;event.currentTarget.reset();populateEventSources();$('#event-source').value=sourceId;$('#event-inbox').checked=true;render();$('#event-title').focus()});

render();switchView('road');
