const STORAGE_KEY='chronizo.workbench.v1';
const THEME_KEY='chronizo.theme';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const freshState=()=>({projects:[],activeProjectId:null});
let state=load();
let selectedEventRelations=[];
let selectedEventSourceIds=[];
let selectedEventCharacterIds=[];
let selectedEventWorldLabels=[];
let roadMode='sources';
let sourceTagFilter='all';
let sourceColorMode='medium';
const SOURCE_PAGE_SIZE=160;
let sourcePage=0;
const viewSearch={road:'',sources:'',worlds:'',characters:'',events:''};
let selectedCharacterId=null;
let editingSourceId=null;
let editingEventId=null;
let editingCharacterId=null;
let editingWorldId=null;
let quickEventSourceId=null;
let worldDialogTarget=null;
let sourceDialogTarget=null;
let characterDialogTarget=null;
let selectedRelatedSourceIds=[];
const RELATION_TYPES=new Set(['before','after','parallel']);

function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return parsed&&Array.isArray(parsed.projects)?parsed:freshState()}catch{return freshState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function activeProject(){return state.projects.find(project=>project.id===state.activeProjectId)||null}
function projectWorlds(){const project=activeProject();if(!project)return[];return project.worlds||(project.worlds=[])}
function worldLabel(world){return world.designation||(world.number?`Earth-${world.number}`:world.name)||'Świat bez oznaczenia'}
function projectCharacters(){const project=activeProject();if(!project)return[];return project.characters||(project.characters=[])}
function characterAliases(character){return [...new Set([...(character.aliases||[]),character.alterEgo].filter(Boolean))]}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function openDialog(selector){const dialog=$(selector);dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type="checkbox"]),textarea,select')?.focus())}
function applyTheme(theme=localStorage.getItem(THEME_KEY)||'green'){document.body.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);const names={shield:'Tarcza Kapitana',green:'Zielony Chronizo',dark:'Ciemny',light:'Jasny'};$('#theme-button').title=`Motyw: ${names[theme]||names.green}`;$('#theme-button').textContent=theme==='shield'?'⭑':theme==='light'?'☀':theme==='dark'?'◐':'◉'}
function ensureThemeDialog(){if($('#theme-dialog'))return;const dialog=document.createElement('dialog');dialog.id='theme-dialog';dialog.className='dialog theme-dialog';dialog.innerHTML='<form method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">WYGLĄD</p><h2>Wybierz motyw Chronizo</h2><div class="theme-options"><button type="button" data-theme-choice="shield"><i></i><b>Tarcza Kapitana</b><small>Czerwień, biel i granat</small></button><button type="button" data-theme-choice="green"><i></i><b>Zielony Chronizo</b><small>Dotychczasowy wygląd</small></button><button type="button" data-theme-choice="dark"><i></i><b>Ciemny</b><small>Neutralna nocna kronika</small></button><button type="button" data-theme-choice="light"><i></i><b>Jasny</b><small>Do czytania w dzień</small></button></div></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelectorAll('[data-theme-choice]').forEach(button=>button.onclick=()=>{applyTheme(button.dataset.themeChoice);dialog.close()})}
function openThemeDialog(){ensureThemeDialog();openDialog('#theme-dialog')}
function empty(icon,title,copy,action='',buttonId=''){return `<div class="empty-state"><div class="empty-state-inner"><div class="empty-icon">${icon}</div><h2>${title}</h2><p>${copy}</p>${action?`<button id="${buttonId}" class="primary-button" type="button">${action}</button>`:''}</div></div>`}

function renderProjectSelect(){const select=$('#project-select');select.innerHTML='';if(!state.projects.length){const option=document.createElement('option');option.textContent='Brak projektu';option.value='';select.append(option);select.disabled=true;return}select.disabled=false;state.projects.forEach(project=>{const option=document.createElement('option');option.value=project.id;option.textContent=project.name;option.selected=project.id===state.activeProjectId;select.append(option)})}
function dateLabel(value,approx=false){if(!value)return 'data nieustalona';return (approx?'około ':'')+escapeHtml(value)}
function itemActions(type,id){return `<div class="item-actions"><button class="edit-${type}" data-id="${id}" type="button" title="Edytuj">✎</button><button class="delete-${type}" data-id="${id}" type="button" title="Usuń">×</button></div>`}
function releaseLabel(value){return value?`premiera: ${escapeHtml(value)}`:'premiera nieustalona'}
function sourceWorldLabels(source){const ids=new Set(source.worldIds||[]);return projectWorlds().filter(world=>ids.has(world.id)).map(worldLabel)}
function sourceTags(source){return [...new Set((source.tags||[]).map(tag=>String(tag).trim().toUpperCase()).filter(Boolean))]}
function importSheetPosition(key=''){const match=String(key).match(/^(extended|multiversal)-vo-(\d+)$/);if(match)return{tag:match[1]==='extended'?'EMCU':'MVO',row:Number(match[2])};return /^mini-verse-vo-\d+$/.test(String(key))?{tag:'MVO',row:null}:null}
function rememberSheetPosition(source,tag,row){if(!Number.isFinite(Number(row)))return false;source.sheetRows=source.sheetRows||{};if(source.sheetRows[tag]===Number(row))return false;source.sheetRows[tag]=Number(row);return true}
function migrateLegacySourceTags(){let changed=false;for(const project of state.projects){for(const source of project.sources||[]){const keys=[source.importKey,...(source.importKeys||[])].filter(Boolean),tags=sourceTags(source),legacyTag=source.importOrigin==='Extended VO'||keys.some(key=>key.startsWith('extended-vo-'))?'EMCU':source.importOrigin==='Multiversal VO'||keys.some(key=>key.startsWith('multiversal-vo-'))?'MVO':null;if(legacyTag&&!tags.includes(legacyTag)){source.tags=[...tags,legacyTag];changed=true}for(const key of keys){const position=importSheetPosition(key);if(position)changed=rememberSheetPosition(source,position.tag,position.row)||changed}}}if(changed)save()}
function metadataKey(value=''){return String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘]/g,"'").replace(/[–—]/g,'-').replace(/\s+/g,' ').trim()}
function universeMetadataKey(value=''){return metadataKey(value).replace(/^earth-/,'').replace(/[✩★*]+$/,'').replace(/\s+/g,'')}
function universeMetadataAliases(value=''){const aliases=[];for(const part of String(value).split('/').map(item=>item.trim()).filter(Boolean)){aliases.push(part);const aka=part.match(/^(.+?)\s*\(AKA\s+(.+?)\)$/i);if(aka)aliases.push(aka[1],aka[2])}return [...new Set(aliases.map(universeMetadataKey).filter(Boolean))]}
function releaseDateIso(value=''){const months={jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'},match=String(value).trim().match(/^([A-Za-z]{3})\s+(\d{1,2}),\s*(\d{4})$/);return match&&months[match[1].toLowerCase()]?`${match[3]}-${months[match[1].toLowerCase()]}-${String(match[2]).padStart(2,'0')}`:''}
async function enrichSourceMetadata(){try{const response=await fetch('data/source-metadata.json?v=1');if(!response.ok)return;const metadata=await response.json();if(metadata.format!=='chronizo-source-metadata')return;const releases=new Map();for(const release of metadata.releases||[]){const key=metadataKey(release.title);if(!releases.has(key))releases.set(key,release)}const universes=new Map();for(const universe of metadata.universes||[])for(const key of universeMetadataAliases(universe.designation))if(!universes.has(key))universes.set(key,universe);let changed=false;for(const project of state.projects){for(const source of project.sources||[]){const imported=[source.importKey,...(source.importKeys||[])].some(key=>importSheetPosition(key));if(!imported||source.releaseDate)continue;const release=releases.get(metadataKey(source.title)),date=releaseDateIso(release?.date);if(date){source.releaseDate=date;source.releaseOrderRow=release.row;changed=true}}for(const world of project.worlds||[]){const importedDescription=!world.description||/ · import$/i.test(world.description);if(!importedDescription)continue;const universe=universes.get(universeMetadataKey(worldLabel(world)));if(universe?.description&&world.description!==universe.description){world.description=universe.description;world.universeIndexRow=universe.row;changed=true}}}if(changed){save();render()}}catch(error){console.warn('Chronizo metadata enrichment skipped',error)}}
const MVO_MINI_VERSE_ADDITIONS=[
 ['mini-verse-vo-419',2418.1,'Meet Spidey and His Amazing Friends Season 1 Episode 1: WEB-STER'],
 ['mini-verse-vo-420',2418.2,'Meet Spidey and His Amazing Friends Season 1 Episode 2: S.O.S Kitty'],
 ['mini-verse-vo-421',2418.3,'Meet Spidey and His Amazing Friends Season 1 Episode 3: Spidey Mystery'],
 ['mini-verse-vo-422',2418.4,'Meet Spidey and His Amazing Friends Season 1 Episode 4: A Helping Hulk'],
 ['mini-verse-vo-423',2418.5,'Meet Spidey and His Amazing Friends Season 1 Episode 5: Spidey Surprise'],
 ['mini-verse-vo-424',2418.6,'Meet Spidey and His Amazing Friends Season 1 Episode 6: Rock-a-Bye Rhino'],
 ['mini-verse-vo-425',2418.7,'Meet Spidey and His Amazing Friends Season 1 Episode 7: Stop Doc Ock'],
 ['mini-verse-vo-426',2418.8,'Meet Spidey and His Amazing Friends Season 1 Episode 8: The Spidey Team'],
 ['mini-verse-vo-427',2418.9,'Meet Spidey and His Amazing Friends Season 1 Episode 9: Monkeying Around']
];
function migrateMvoMiniVerseSources(){const migration='mvo-mini-verse-9-v2-order-repair',projects=state.projects.filter(project=>!(project.catalogMigrations||[]).includes(migration)&&(project.sources||[]).some(source=>sourceTags(source).includes('MVO')));if(!projects.length)return;for(const project of projects){project.worlds=project.worlds||[];project.sources=project.sources||[];let world=project.worlds.find(item=>universeMetadataKey(worldLabel(item))==='21642');if(!world){world={id:uid('world'),designation:'Earth-21642',name:'Earth-21642',description:'Multiversal VO · import'};project.worlds.push(world)}for(const [importKey,orderRow,title] of MVO_MINI_VERSE_ADDITIONS){const existing=project.sources.find(source=>source.importKey===importKey||(source.importKeys||[]).includes(importKey));if(existing){rememberSheetPosition(existing,'MVO',orderRow);continue}project.sources.push({id:uid('source'),importKey,importKeys:[importKey],importOrigin:'Mini-Verse VOs',title,type:'Serial',status:'Nierozpoczęte',date:'Jun, 2019',dateApprox:false,releaseDate:'2021-06-21',tags:['MVO'],sheetRows:{MVO:orderRow},worldIds:[world.id],createdAt:new Date().toISOString()})}project.catalogMigrations=[...(project.catalogMigrations||[]),migration]}save();render()}
async function runCatalogMigrations(){await migrateMvoMiniVerseSources();await enrichSourceMetadata()}
function sourceTagMarkup(source){return sourceTags(source).map(tag=>`<span class="tag source-hashtag">#${escapeHtml(tag)}</span>`).join('')}
function sourceRelationLabel(type){return({adaptation:'adaptacja',prequel:'prequel',tiein:'tie-in',promotional:'materiał promocyjny',associated:'nieoficjalnie łączony'})[type]||''}
function relatedSources(source){const ids=new Set(source.relatedSourceIds||[]);return (activeProject()?.sources||[]).filter(item=>ids.has(item.id))}
function sourcePalette(source){const medium={Film:'#287cff',Serial:'#8657e8',Komiks:'#ef3f4f',Książka:'#e0a51c',Gra:'#13b977',Inne:'#27aeb7'},tag={EMCU:'#df3348',MVO:'#35b84a'},tags=sourceTags(source),tagColor=tags.includes('EMCU')?tag.EMCU:tags.includes('MVO')?tag.MVO:'#2bc5a2',colors=sourceColorMode==='tag'?[tagColor]:[medium[source.type]||medium.Inne],strength=source.status==='Ukończone'||source.status==='Opracowane'?62:source.status==='Rozpoczęte'?40:18,mixes=colors.map(color=>`color-mix(in srgb,${color} ${strength}%,var(--panel2))`);return `--source-bg:${mixes[0]};--source-accent:${colors[0]||'#27aeb7'}`}
function sourceRow(source){const worlds=sourceWorldLabels(source),links=relatedSources(source),relation=sourceRelationLabel(source.relationType);return `<article class="list-item source-item" style="${sourcePalette(source)}"><span class="list-mark">▤</span><div class="list-copy"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)} · akcja: ${dateLabel(source.date,source.dateApprox)} · ${releaseLabel(source.releaseDate)}</small>${links.length?`<small class="source-relation-line">↳ ${escapeHtml(relation||'powiązane')} z: ${escapeHtml(links.map(item=>item.title).join(' · '))}</small>`:''}<div class="tag-row">${sourceTagMarkup(source)}${relation?`<span class="tag movie-comic-tag">${escapeHtml(relation)}</span>`:''}${source.canonStatus?`<span class="tag canon-tag">${escapeHtml(source.canonStatus)}</span>`:''}${worlds.map(world=>`<span class="tag">${escapeHtml(world)}</span>`).join('')}</div></div><span class="status">${escapeHtml(source.status)}</span><div class="source-actions"><button class="add-event-from-source mini-button" data-id="${source.id}" type="button" title="Dodaj wydarzenie z tego źródła" aria-label="Dodaj wydarzenie z tego źródła">＋●</button>${itemActions('source',source.id)}</div></article>`}
function allSourceTags(){return [...new Set((activeProject()?.sources||[]).flatMap(sourceTags))].sort()}
function filteredSources(){const sources=activeProject()?.sources||[];return sourceTagFilter==='all'?sources:sources.filter(source=>sourceTags(source).includes(sourceTagFilter))}
function sourceControls(){const tags=allSourceTags();return `<div class="source-controls"><div class="source-tag-filters"><button class="${sourceTagFilter==='all'?'active':''}" data-source-tag="all" type="button">Wszystkie</button>${tags.map(tag=>`<button class="${sourceTagFilter===tag?'active':''}" data-source-tag="${escapeHtml(tag)}" type="button">#${escapeHtml(tag)}</button>`).join('')}</div><label>Kolor tła<select data-source-color><option value="medium" ${sourceColorMode==='medium'?'selected':''}>według medium</option><option value="tag" ${sourceColorMode==='tag'?'selected':''}>według hashtagu</option></select></label></div>`}
function bindSourceControls(root=document){root.querySelectorAll('[data-source-tag]').forEach(button=>button.addEventListener('click',()=>{sourceTagFilter=button.dataset.sourceTag;sourcePage=0;renderSources();renderRoad()}));root.querySelectorAll('[data-source-color]').forEach(select=>select.addEventListener('change',()=>{sourceColorMode=select.value;renderSources();renderRoad()}))}
function eventSourceIds(event){return [...new Set([event.sourceId,...(event.sourceIds||[])].filter(Boolean))]}
function eventRelations(event){if(Array.isArray(event.relations))return event.relations.filter(relation=>RELATION_TYPES.has(relation.type)&&relation.eventId);return RELATION_TYPES.has(event.timeType)&&event.relationEventId?[{type:event.timeType,eventId:event.relationEventId}]:[]}
function eventSources(event){const ids=eventSourceIds(event);return (activeProject()?.sources||[]).filter(source=>ids.includes(source.id))}
function chronologyKey(value=''){const text=String(value).trim(),normalized=text.replace(/,/g,'');if(!text)return Number.POSITIVE_INFINITY;if(/^(beginning of time|początek czasu)$/i.test(text))return Number.NEGATIVE_INFINITY;let match=normalized.match(/^(-?\d+(?:\.\d+)?)\s*(BC|BCE|p\.n\.e\.)$/i);if(match)return-Number(match[1]);match=normalized.match(/^(-?\d+(?:\.\d+)?)\s*(AD|CE|n\.e\.)?$/i);if(match)return Number(match[1]);match=text.match(/^(-?\d{1,6})-(\d{2})-(\d{2})$/);if(match)return Number(match[1])+Number(match[2])/12+Number(match[3])/372;return Number.POSITIVE_INFINITY}
function sourceSheetRow(source){const rows=source.sheetRows||{},preferred=sourceTagFilter!=='all'?rows[sourceTagFilter]:rows.MVO??rows.EMCU;if(Number.isFinite(Number(preferred)))return Number(preferred);const positions=[source.importKey,...(source.importKeys||[])].map(importSheetPosition).filter(Boolean),match=sourceTagFilter==='all'?positions.find(position=>position.tag==='MVO')||positions.find(position=>position.tag==='EMCU'):positions.find(position=>position.tag===sourceTagFilter);return match?.row??Number.POSITIVE_INFINITY}
function chronologicalCompare(a,b){const difference=chronologyKey(a.date)-chronologyKey(b.date);if(!Number.isNaN(difference)&&difference!==0)return difference;const sheetDifference=sourceSheetRow(a)-sourceSheetRow(b);return !Number.isNaN(sheetDifference)&&sheetDifference!==0?sheetDifference:(a.createdAt||'').localeCompare(b.createdAt||'')}
function sourceCatalogCompare(a,b){if(sourceTagFilter==='all'||sourceTagFilter==='MVO'){const sheetDifference=sourceSheetRow(a)-sourceSheetRow(b);if(!Number.isNaN(sheetDifference)&&sheetDifference!==0)return sheetDifference}return chronologicalCompare(a,b)}
function matchesViewSearch(view,values){const query=metadataKey(viewSearch[view]);return !query||metadataKey(values.filter(Boolean).join(' ')).includes(query)}
function sourceMatchesSearch(source,view){return matchesViewSearch(view,[source.title,source.type,source.status,source.date,source.releaseDate,sourceRelationLabel(source.relationType),source.canonStatus,...sourceTags(source),...sourceWorldLabels(source),...relatedSources(source).map(item=>item.title)])}
function eventMatchesSearch(event,view){return matchesViewSearch(view,[relationHaystack(event),event.date,event.timeType,...eventRelations(event).map(relation=>relation.type)])}
function characterMatchesSearch(character){return matchesViewSearch('characters',[character.name,...characterAliases(character),character.world,character.birthDate,character.deathDate])}
function earliestDate(values){return values.filter(Boolean).sort((a,b)=>chronologyKey(a)-chronologyKey(b))[0]||''}
function eventChronologyDate(event){return event.date||earliestDate(eventSources(event).map(source=>source.date))}
function orderEventsChronologically(events){const ordered=events.slice().sort((a,b)=>{const difference=chronologyKey(eventChronologyDate(a))-chronologyKey(eventChronologyDate(b));return Number.isNaN(difference)||difference===0?(a.createdAt||'').localeCompare(b.createdAt||''):difference});for(let pass=0;pass<ordered.length*2;pass++){let changed=false;for(const event of [...ordered]){for(const relation of eventRelations(event)){const from=ordered.indexOf(event),target=ordered.findIndex(item=>item.id===relation.eventId);if(target<0)continue;const wantsBefore=relation.type==='before',wrong=wantsBefore?from>target:relation.type==='after'?from<target:Math.abs(from-target)>1;if(!wrong)continue;ordered.splice(from,1);const nextTarget=ordered.findIndex(item=>item.id===relation.eventId);ordered.splice(wantsBefore?nextTarget:nextTarget+1,0,event);changed=true;break}}if(!changed)break}return ordered}
function roadNode(item,index){if(roadMode==='sources')return `<article class="road-node source-item ${index%2?'branch-down':'branch-up'}" style="${sourcePalette(item)}"><span class="road-dot"></span><small>${dateLabel(item.date,item.dateApprox)}</small><b>${escapeHtml(item.title)}</b><em>${escapeHtml(item.type)} · ${escapeHtml(item.status)}<br>${releaseLabel(item.releaseDate)}</em><div class="tag-row">${sourceTagMarkup(item)}</div>${itemActions('source',item.id)}</article>`;const sources=eventSources(item),characters=projectCharacters().filter(character=>(item.characterIds||[]).includes(character.id));return `<article class="road-node ${index%2?'branch-down':'branch-up'}"><span class="road-dot"></span><small>${dateLabel(eventChronologyDate(item),item.dateApprox??item.timeType==='approx')}</small><b>${escapeHtml(item.title)}</b><em>${escapeHtml([item.world,item.place,...sources.map(source=>source.title)].filter(Boolean).join(' · ')||'Bez przypisania')}</em>${characters.length?`<span class="road-people">${characters.map(character=>escapeHtml(character.name)).join(' · ')}</span>`:''}${itemActions('event',item.id)}</article>`}
function roadItemsMarkup(items){if(roadMode!=='sources')return items.map(roadNode).join('');const groups=new Map();for(const source of items){const worlds=sourceWorldLabels(source).sort(),key=worlds.length?worlds.join(' + '):'Bez przypisanego świata';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(source)}return [...groups].sort(([a],[b])=>a.localeCompare(b,'pl')).map(([world,sources])=>`<section class="road-world-lane"><h3>${sources.some(source=>sourceWorldLabels(source).length>1)?'⇄ Połączenie · ':''}${escapeHtml(world)} <span>${sources.length}</span></h3><div class="road-lane-scroll"><div class="road-lane-track">${sources.map(roadNode).join('')}</div></div></section>`).join('')}
function exportProject(){const project=activeProject();if(!project)return;const payload={format:'chronizo-project',version:1,exportedAt:new Date().toISOString(),project},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(project.name||'chronizo').replace(/[^a-z0-9ąćęłńóśźż-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'.chronizo.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importProjectFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result),source=payload.format==='chronizo-project'?payload.project:payload;if(!source||typeof source.name!=='string'||!Array.isArray(source.sources)||!Array.isArray(source.events))throw new Error('Nieprawidłowy format');const project=structuredClone(source);project.id=uid('project');project.name=source.name+' · import';project.worlds=Array.isArray(project.worlds)?project.worlds:[];project.characters=Array.isArray(project.characters)?project.characters:[];state.projects.push(project);state.activeProjectId=project.id;save();render();switchView('road')}catch{alert('Nie udało się wczytać projektu. Wybierz plik JSON wyeksportowany z Chronizo.')}};reader.readAsText(file)}
function extendedUniverseLabels(value=''){return String(value).split('/').map(part=>part.trim()).filter(Boolean).map(part=>part==='FW'?'Framework':/^\d+[✩★]?$/.test(part)?`Earth-${part}`:part)}
function sourceIdentity(title,date,worlds){const normal=value=>String(value||'').toLowerCase().replace(/\s+/g,' ').trim();return [normal(title),normal(date),[...worlds].map(normal).sort().join('/')].join('|')}
async function importSourcePack({url,buttonId,label,tag}){const project=activeProject(),button=$(buttonId);if(!project)return openDialog('#project-dialog');button.disabled=true;button.textContent=`Wczytuję ${label}…`;try{const response=await fetch(url);if(!response.ok)throw new Error('Nie udało się pobrać paczki');const pack=await response.json();if(pack.format!=='chronizo-source-pack'||!Array.isArray(pack.sources))throw new Error('Nieprawidłowa paczka źródeł');let added=0,merged=0,worldsAdded=0;for(const packed of pack.sources){const labels=extendedUniverseLabels(packed.universe),worldIds=[];for(const designation of labels){let world=projectWorlds().find(item=>worldLabel(item).toLowerCase()===designation.toLowerCase());if(!world){world={id:uid('world'),designation,name:designation,description:`${label} · import`};projectWorlds().push(world);worldsAdded++}worldIds.push(world.id)}const identity=sourceIdentity(packed.title,packed.date,labels),byImport=(project.sources||[]).find(source=>source.importKey===packed.importKey||(source.importKeys||[]).includes(packed.importKey)),existing=byImport||(project.sources||[]).find(source=>sourceIdentity(source.title,source.date,sourceWorldLabels(source))===identity),orderRow=packed.orderRow??packed.row;if(existing){existing.tags=[...new Set([...sourceTags(existing),...(packed.tags||[]),tag].filter(Boolean))];existing.importKeys=[...new Set([...(existing.importKeys||[]),existing.importKey,packed.importKey].filter(Boolean))];existing.worldIds=[...new Set([...(existing.worldIds||[]),...worldIds])];rememberSheetPosition(existing,tag,orderRow);merged++;continue}project.sources.push({id:uid('source'),importKey:packed.importKey,importKeys:[packed.importKey],importOrigin:packed.sourceSheet||label,title:packed.title,type:packed.type||'Inne',status:'Nierozpoczęte',date:packed.date||'',dateApprox:Boolean(packed.dateApprox),releaseDate:packed.releaseDate||'',tags:[...new Set([...(packed.tags||[]),tag].filter(Boolean))],sheetRows:{[tag]:Number(orderRow)},worldIds,createdAt:new Date().toISOString()});added++}save();render();switchView('sources');alert(`${label}: dodano ${added}, połączono lub zaktualizowano ${merged}, utworzono ${worldsAdded} światów.`)}catch(error){alert(`Import ${label} nie powiódł się: ${error.message}`)}finally{button.disabled=false;button.textContent=`↓ Wczytaj ${label}`}}
async function importSourcePackFast({url,buttonId,label,tag}){
 const project=activeProject(),button=$(buttonId);
 if(!project)return openDialog('#project-dialog');
 button.disabled=true;button.textContent=`Wczytuję ${label}…`;
 try{
  const response=await fetch(url);if(!response.ok)throw new Error('Nie udało się pobrać paczki');
  const pack=await response.json();if(pack.format!=='chronizo-source-pack'||!Array.isArray(pack.sources))throw new Error('Nieprawidłowa paczka źródeł');
  const worlds=projectWorlds(),worldMap=new Map(worlds.map(world=>[worldLabel(world).toLowerCase(),world])),imports=new Map(),identities=new Map();
  for(const source of project.sources||[]){for(const key of [source.importKey,...(source.importKeys||[])].filter(Boolean))imports.set(key,source);identities.set(sourceIdentity(source.title,source.date,sourceWorldLabels(source)),source)}
  let added=0,merged=0,worldsAdded=0;
  for(const packed of pack.sources){
   const labels=extendedUniverseLabels(packed.universe),identity=sourceIdentity(packed.title,packed.date,labels);
   const existing=imports.get(packed.importKey)||identities.get(identity),orderRow=packed.orderRow??packed.row;
   if(existing){existing.tags=[...new Set([...sourceTags(existing),...(packed.tags||[]),tag].filter(Boolean))];existing.importKeys=[...new Set([...(existing.importKeys||[]),existing.importKey,packed.importKey].filter(Boolean))];rememberSheetPosition(existing,tag,orderRow);imports.set(packed.importKey,existing);identities.set(identity,existing);merged++;continue}
   const worldIds=[];
   for(const designation of labels){const key=designation.toLowerCase();let world=worldMap.get(key);if(!world){world={id:uid('world'),designation,name:designation,description:`${label} · import`};worlds.push(world);worldMap.set(key,world);worldsAdded++}worldIds.push(world.id)}
   const created={id:uid('source'),importKey:packed.importKey,importKeys:[packed.importKey],importOrigin:packed.sourceSheet||label,title:packed.title,type:packed.type||'Inne',status:'Nierozpoczęte',date:packed.date||'',dateApprox:Boolean(packed.dateApprox),releaseDate:packed.releaseDate||'',tags:[...new Set([...(packed.tags||[]),tag].filter(Boolean))],sheetRows:{[tag]:Number(orderRow)},worldIds,createdAt:new Date().toISOString()};
   project.sources.push(created);imports.set(packed.importKey,created);identities.set(identity,created);added++;
  }
  save();render();switchView('sources');void enrichSourceMetadata();alert(`${label}: dodano ${added}, połączono lub oznaczono hashtagami ${merged}, utworzono ${worldsAdded} światów.`);
 }catch(error){alert(`Import ${label} nie powiódł się: ${error.message}`)}
 finally{button.disabled=false;button.textContent=`↓ Wczytaj ${label}`}
}
function importExtendedVo(){return importSourcePackFast({url:'data/extended-vo.sources.json?v=2',buttonId:'#import-extended-vo',label:'Extended VO',tag:'EMCU'})}
function importMultiversalVo(){return importSourcePackFast({url:'data/multiversal-vo.sources.json?v=2',buttonId:'#import-multiversal-vo',label:'Multiversal VO',tag:'MVO'})}
function renderRoad(){
 const project=activeProject(),content=$('#road-content'),button=$('#new-project-main');
 if(!project){$('#road-title').textContent='Zacznij własną kronikę';$('#road-subtitle').textContent='Bez przykładów. Bez narzuconego uniwersum. To miejsce czeka na Twoją historię.';button.textContent='Utwórz pierwszy projekt';content.innerHTML=empty('◫','Tabula rasa','Utwórz projekt, nadaj mu własną nazwę i zacznij dodawać materiały. Chronizo nie wstawia żadnych przykładowych światów, postaci ani wydarzeń.','Utwórz projekt','empty-new-project');$('#empty-new-project').onclick=()=>openDialog('#project-dialog');return}
 const allSources=project.sources||[],allEvents=project.events||[],focusedCharacter=projectCharacters().find(character=>character.id===selectedCharacterId)||null,characterEvents=focusedCharacter?allEvents.filter(event=>(event.characterIds||[]).includes(focusedCharacter.id)):allEvents,events=characterEvents.filter(event=>eventMatchesSearch(event,'road')),sourceIds=new Set(characterEvents.flatMap(eventSourceIds)),sources=focusedCharacter?allSources.filter(source=>sourceIds.has(source.id)):allSources,inbox=characterEvents.filter(event=>event.inbox),orderedSources=filteredSources().filter(source=>(!focusedCharacter||sourceIds.has(source.id))&&sourceMatchesSearch(source,'road')).slice().sort(sourceCatalogCompare),orderedEvents=orderEventsChronologically(events),allRoadItems=roadMode==='events'?orderedEvents:orderedSources,roadItems=roadMode==='sources'?allRoadItems.slice(0,300):allRoadItems;
 $('#road-title').textContent=project.name;$('#road-subtitle').textContent=project.description||'Twoja droga przez źródła i wydarzenia.';button.textContent='＋ Dodaj źródło';
 content.innerHTML=`<div class="road-top"><div class="road-modes" role="tablist" aria-label="Sposób budowania drogi"><button class="${roadMode==='sources'?'active':''}" data-road-mode="sources" type="button">▤ Według źródeł</button><button class="${roadMode==='events'?'active':''}" data-road-mode="events" type="button">● Chronologia wydarzeń</button></div><div class="project-data-actions"><button id="import-project" class="secondary-button" type="button">↑ Importuj projekt</button><button id="export-project" class="primary-button" type="button">↓ Eksportuj projekt</button><input id="import-project-file" type="file" accept="application/json,.json" hidden></div></div><div class="panel road-panel"><div class="panel-head"><h2>${roadMode==='events'?'Chronologia wydarzeń':'Kolejność źródeł według światów'}</h2><span class="counter">${roadItems.length}</span></div>${roadItems.length?`<div class="road-scroll"><div class="road-track">${roadItemsMarkup(roadItems)}</div></div>`:empty(roadMode==='events'?'●':'▤',roadMode==='events'?'Brak wydarzeń':'Droga jest jeszcze pusta',roadMode==='events'?'Dodaj pierwsze wydarzenie, aby zacząć budować chronologię.':'Dodaj pierwszy film, serial, komiks albo inne źródło.',roadMode==='events'?'Dodaj wydarzenie':'Dodaj źródło','road-add-item')}</div><div class="road-summary"><div class="panel"><div class="panel-head"><h2>Stan kroniki</h2></div><div class="metric-grid"><div class="metric"><strong>${sources.length}</strong><span>źródła</span></div><div class="metric"><strong>${events.length}</strong><span>wydarzenia</span></div><div class="metric"><strong>${inbox.length}</strong><span>do uporządkowania</span></div></div></div></div>`;
 if(focusedCharacter){content.querySelector('.road-top').insertAdjacentHTML('afterend',`<div class="character-focus-banner"><span>♙</span><div><small>DROGA POSTACI</small><b>${escapeHtml(focusedCharacter.name)}</b><em>${events.length} wydarzeń · ${sources.length} źródeł</em></div><button id="clear-character-focus" type="button">Pokaż całą kronikę ×</button></div>`);$('#clear-character-focus').onclick=()=>{selectedCharacterId=null;renderRoad()}}
 $$('.road-modes button').forEach(mode=>mode.addEventListener('click',()=>{roadMode=mode.dataset.roadMode;renderRoad()}));
 $('#road-add-item')?.addEventListener('click',()=>roadMode==='events'?openEventDialog():openSourceDialog());
 $('#export-project')?.addEventListener('click',exportProject);
 $('#import-project')?.addEventListener('click',()=>$('#import-project-file').click());
 $('#import-project-file')?.addEventListener('change',event=>{importProjectFile(event.target.files[0]);event.target.value=''})
}
function bindProjectEmpty(id){$('#'+id)?.addEventListener('click',()=>openDialog('#project-dialog'))}
function renderSources(){const project=activeProject(),content=$('#sources-content');if(!project){content.innerHTML=empty('▤','Najpierw utwórz projekt','Każde źródło należy do konkretnej drogi.','Utwórz projekt','sources-new-project');bindProjectEmpty('sources-new-project');return}const sources=project.sources||[],filtered=filteredSources().filter(source=>sourceMatchesSearch(source,'sources')).slice().sort(sourceCatalogCompare),pageCount=Math.max(1,Math.ceil(filtered.length/SOURCE_PAGE_SIZE));sourcePage=Math.min(sourcePage,pageCount-1);const start=sourcePage*SOURCE_PAGE_SIZE,visible=filtered.slice(start,start+SOURCE_PAGE_SIZE),pagination=filtered.length>SOURCE_PAGE_SIZE?`<nav class="source-pagination" aria-label="Strony źródeł"><button id="previous-sources" class="secondary-button" type="button" ${sourcePage===0?'disabled':''}>← Wstecz</button><span>Strona ${sourcePage+1} z ${pageCount}</span><button id="next-sources" class="secondary-button" type="button" ${sourcePage>=pageCount-1?'disabled':''}>Dalej →</button></nav>`:'';content.innerHTML=sources.length?`${sourceControls()}<div class="panel"><div class="panel-head"><h2>Materiały według daty akcji</h2><span class="counter">${filtered.length} / ${sources.length}</span></div>${visible.length?`<div class="list">${visible.map(sourceRow).join('')}</div>${pagination}`:'<p class="panel-note">Nie znaleziono źródeł pasujących do filtrów.</p>'}</div>`:empty('▤','Brak źródeł','Dodaj pierwszy materiał bez gotowych przykładów i sztucznego wypełniania.','Dodaj źródło','sources-add-first');bindSourceControls(content);$('#previous-sources')?.addEventListener('click',()=>{sourcePage=Math.max(0,sourcePage-1);renderSources();scrollTo({top:0,behavior:'smooth'})});$('#next-sources')?.addEventListener('click',()=>{sourcePage=Math.min(pageCount-1,sourcePage+1);renderSources();scrollTo({top:0,behavior:'smooth'})});$('#sources-add-first')?.addEventListener('click',()=>openSourceDialog())}
function renderWorlds(){const project=activeProject(),content=$('#worlds-content');if(!project){content.innerHTML=empty('◉','Najpierw utwórz projekt','Światy będą należały do wybranej kroniki.','Utwórz projekt','worlds-new-project');bindProjectEmpty('worlds-new-project');return}const allWorlds=projectWorlds(),worlds=allWorlds.filter(world=>matchesViewSearch('worlds',[worldLabel(world),world.description])),sources=project.sources||[],events=project.events||[];content.innerHTML=allWorlds.length?`<div class="panel"><div class="panel-head"><h2>Kartoteka światów</h2><span class="counter">${worlds.length} / ${allWorlds.length}</span></div>${worlds.length?`<div class="list">${worlds.map(world=>{const label=worldLabel(world),sourceCount=sources.filter(source=>(source.worldIds||[]).includes(world.id)).length,eventCount=events.filter(event=>event.world===label||(event.worldLinks||[]).includes(label)).length;return `<article class="list-item world-item"><span class="list-mark">◉</span><div class="list-copy"><b>${escapeHtml(label)}</b><small>${escapeHtml(world.description||'Bez krótkiego opisu')}</small><div class="tag-row">${world.draft?'<span class="tag draft-tag">do uzupełnienia</span>':''}<span class="tag">${sourceCount} źródeł</span><span class="tag">${eventCount} wydarzeń</span></div></div>${itemActions('world',world.id)}</article>`}).join('')}</div>`:'<p class="panel-note">Nie znaleziono pasującego świata.</p>'}</div>`:empty('◉','Brak światów','Dodaj pierwszą rzeczywistość, linię czasową albo wymiar metafizyczny.','Dodaj świat','worlds-add-first');$('#worlds-add-first')?.addEventListener('click',()=>openWorldDialog())}
function timeLabel(type){return({exact:'dokładnie',approx:'około',before:'przed',after:'po',parallel:'równolegle',order:'kolejność',unknown:'nieustalone'})[type]||'nieustalone'}
function eventRow(event){const project=activeProject(),sources=eventSources(event),primary=sources.find(source=>source.id===event.sourceId)||sources[0],characters=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)),relations=eventRelations(event).map(relation=>{const related=(project.events||[]).find(item=>item.id===relation.eventId);return related?`<small class="event-relation">↳ ${timeLabel(relation.type)}: ${escapeHtml(related.title)}</small>`:''}).join(''),effectiveDate=event.date||sources.map(source=>source.date).filter(Boolean).sort()[0],worldLinks=(event.worldLinks||[]).filter(name=>name&&name!==event.world),meeting=worldLinks.length?`<span class="tag convergence-tag">spotkanie: ${escapeHtml(worldLinks.join(' + '))}</span>`:'',sourceNames=sources.map(source=>source.title).join(' · '),placement=[event.date?(event.dateApprox?'około':'data'):null,eventRelations(event).length?`${eventRelations(event).length} rel.`:null].filter(Boolean).join(' + ')||'nieustalone';return `<article class="list-item"><span class="list-mark">●</span><div class="list-copy"><b>${escapeHtml(event.title)}</b><small>${escapeHtml(sourceNames||'Bez przypisanego źródła')} · ${dateLabel(effectiveDate,event.date?event.dateApprox:primary?.dateApprox)}</small>${relations}<div class="tag-row">${event.world?`<span class="tag">${escapeHtml(event.world)}</span>`:''}${meeting}${event.place?`<span class="tag">${escapeHtml(event.place)}</span>`:''}${characters.map(character=>`<span class="tag character-tag">♙ ${escapeHtml(character.name)}</span>`).join('')}${event.inbox?'<span class="tag inbox-tag">do uporządkowania</span>':''}</div></div><span class="status">${placement}</span>${itemActions('event',event.id)}</article>`}
function renderEvents(){const project=activeProject(),content=$('#events-content');if(!project){content.innerHTML=empty('●','Najpierw utwórz projekt','Wydarzenia będą zapisywane wewnątrz wybranej kroniki.','Utwórz projekt','events-new-project');bindProjectEmpty('events-new-project');return}const allEvents=project.events||[],events=allEvents.filter(event=>eventMatchesSearch(event,'events')).slice().reverse();content.innerHTML=allEvents.length?`<div class="panel"><div class="panel-head"><h2>Dziennik wydarzeń</h2><span class="counter">${events.length} / ${allEvents.length}</span></div>${events.length?`<div class="list">${events.map(eventRow).join('')}</div>`:'<p class="panel-note">Nie znaleziono pasującego wydarzenia.</p>'}</div>`:empty('●','Dziennik jest pusty','Dodaj pierwsze wydarzenie; szczegóły i relacje możesz uzupełnić później.','Dodaj wydarzenie','events-add-first');$('#events-add-first')?.addEventListener('click',()=>openEventDialog())}
function characterConnections(characterId){const project=activeProject(),events=(project?.events||[]).filter(event=>(event.characterIds||[]).includes(characterId)),ids=new Set(events.flatMap(event=>event.characterIds||[]).filter(id=>id!==characterId));return{events,characters:projectCharacters().filter(character=>ids.has(character.id))}}
function characterRow(character){const links=characterConnections(character.id),aliases=characterAliases(character),life=[character.birthDate||'?',character.deathDate||'…'].join(' – ');return `<article class="list-item character-item"><span class="list-mark">♙</span><div class="list-copy"><b>${escapeHtml(character.name)}</b><small>${escapeHtml(aliases.join(' / ')||'Bez alternatywnych imion')} · ${escapeHtml(character.world||'świat nieustalony')} · ${escapeHtml(life)}</small><div class="tag-row">${character.draft?'<span class="tag draft-tag">do uzupełnienia</span>':''}${links.characters.slice(0,6).map(item=>`<span class="tag connection-tag">↔ ${escapeHtml(item.name)}</span>`).join('')}</div></div><span class="status">${links.characters.length} koneksji</span><button class="focus-character mini-button" data-character-focus="${character.id}" type="button" title="Pokaż chronologiczną drogę postaci">⌁</button>${itemActions('character',character.id)}</article>`}
function renderCharacters(){const project=activeProject(),content=$('#characters-content');if(!project){content.innerHTML=empty('♙','Najpierw utwórz projekt','Postacie będą należały do wybranej kroniki.','Utwórz projekt','characters-new-project');bindProjectEmpty('characters-new-project');return}const allCharacters=projectCharacters(),characters=allCharacters.filter(characterMatchesSearch);content.innerHTML=allCharacters.length?`<div class="panel"><div class="panel-head"><h2>Kartoteka postaci</h2><span class="counter">${characters.length} / ${allCharacters.length}</span></div>${characters.length?`<div class="list">${characters.map(characterRow).join('')}</div>`:'<p class="panel-note">Nie znaleziono pasującej postaci.</p>'}</div>`:empty('♙','Brak postaci','Dodaj postać, a następnie przypisuj ją bezpośrednio do wydarzeń.','Dodaj postać','characters-add-first');$('#characters-add-first')?.addEventListener('click',()=>openCharacterDialog())}
function renderAtlas(){const project=activeProject(),events=project?.events||[],worlds=project?projectWorlds():[],connections=events.flatMap(event=>(event.worldLinks||[]).filter(name=>name&&name!==event.world).map(name=>({from:event.world||'Świat nieustalony',to:name,event:event.title})));if(!project||!worlds.length){$('#atlas-content').innerHTML=`<div class="atlas-placeholder"><div class="atlas-grid"></div><div class="atlas-message"><div><div class="empty-icon">⌖</div><h2>${project?'Atlas czeka na światy':'Najpierw utwórz projekt'}</h2><p>${project?'Dodaj pierwszy świat w widoku Road. Każdy pozostanie osobnym węzłem, nawet gdy później spotka się z innym.':'Atlas należy do wybranego projektu i pozostaje całkowicie pusty.'}</p></div></div></div>`;return}$('#atlas-content').innerHTML=`<div class="world-network"><div class="panel-head"><h2>Wszystkie połączone światy</h2><span class="counter">${worlds.length}</span></div><div class="world-nodes">${worlds.map((world,index)=>`<article class="world-node" style="--world-index:${index}"><span>◉</span><b>${escapeHtml(worldLabel(world))}</b><small>${escapeHtml(world.description||'Osobna gałąź projektu')}</small></article>`).join('')}</div><div class="world-bridges">${connections.length?connections.map(link=>`<article><span>${escapeHtml(link.from)}</span><i>→</i><span>${escapeHtml(link.to)}</span><b>${escapeHtml(link.event)}</b></article>`).join(''):'<p class="panel-note">Światy są jeszcze rozdzielone. Spotkanie zapisane w wydarzeniu utworzy tutaj most.</p>'}</div></div>`}
function updateActions(){const hasProject=Boolean(activeProject());$('#quick-event-button').disabled=!hasProject;$('#add-source-button').disabled=!hasProject;$('#add-world-view-button').disabled=!hasProject;$('#add-character-button').disabled=!hasProject;$('#add-event-button').disabled=!hasProject}
function render(){renderProjectSelect();renderRoad();renderSources();renderWorlds();renderCharacters();renderEvents();renderAtlas();updateActions()}
function switchView(view){$$('.view').forEach(section=>section.classList.toggle('active',section.id==='view-'+view));$$('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
function ensureCharacterDialog(){if($('#character-dialog'))return;const dialog=document.createElement('dialog');dialog.id='character-dialog';dialog.className='dialog';dialog.innerHTML='<form id="character-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">POSTAĆ</p><h2>Dodaj postać</h2><label>Nazwa<input id="character-name" required autocomplete="off"></label><label>Alter ego i alternatywne imiona<input id="character-aliases" autocomplete="off" placeholder="Np. Logan, James Howlett, Weapon X"><small>Możesz podać kilka nazw oddzielonych przecinkami.</small></label><label>Świat pochodzenia<div class="inline-field"><input id="character-world" list="project-world-list" autocomplete="off"><button id="add-character-world" class="mini-button" type="button" title="Dodaj nowy świat">＋</button></div></label><div class="form-row"><label>Data urodzenia<input id="character-birth" type="text" autocomplete="off" placeholder="Np. 1920, marzec 1984, około 1943"><small>Wystarczy rok, miesiąc, zakres albo opis.</small></label><label>Data śmierci<input id="character-death" type="text" autocomplete="off" placeholder="Np. 2023, lato 2019, data nieznana"><small>Nie musisz znać dokładnego dnia.</small></label></div><button class="primary-button full" value="save" type="submit">Dodaj postać</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>{characterDialogTarget=null;dialog.close()};dialog.querySelector('#add-character-world').onclick=()=>openWorldDialog('character');dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const name=$('#character-name').value.trim();if(!name)return;const data={name,aliases:$('#character-aliases').value.split(',').map(alias=>alias.trim()).filter(Boolean),world:$('#character-world').value.trim(),birthDate:$('#character-birth').value.trim(),deathDate:$('#character-death').value.trim()};let characterId=editingCharacterId;if(editingCharacterId){const item=projectCharacters().find(character=>character.id===editingCharacterId);if(item){delete item.alterEgo;Object.assign(item,data)}}else{characterId=uid('character');projectCharacters().push({id:characterId,...data})}const target=characterDialogTarget;editingCharacterId=null;characterDialogTarget=null;save();dialog.close();render();if(target==='event'){if(!selectedEventCharacterIds.includes(characterId))selectedEventCharacterIds.push(characterId);populateEventCharacters()}})}
function openCharacterDialog(characterId=null,target=null){if(!activeProject())return openDialog('#project-dialog');ensureWorldFields();ensureCharacterDialog();editingCharacterId=characterId;characterDialogTarget=target;$('#character-form').reset();const item=projectCharacters().find(character=>character.id===characterId);if(item){$('#character-name').value=item.name;$('#character-aliases').value=characterAliases(item).join(', ');$('#character-world').value=item.world||'';$('#character-birth').value=item.birthDate||'';$('#character-death').value=item.deathDate||'';$('#character-dialog h2').textContent='Edytuj postać';$('#character-form .primary-button').textContent='Zapisz zmiany'}else{$('#character-dialog h2').textContent='Dodaj postać';$('#character-form .primary-button').textContent='Dodaj postać'}openDialog('#character-dialog')}
function ensureWorldDialog(){if($('#world-dialog'))return;const dialog=document.createElement('dialog');dialog.id='world-dialog';dialog.className='dialog';dialog.innerHTML='<form id="world-form" method="dialog"><button class="dialog-close" value="cancel" type="button" aria-label="Zamknij">×</button><p class="eyebrow">ŚWIAT</p><h2>Dodaj świat do projektu</h2><label>Numer, nazwa lub oznaczenie<input id="world-designation" required autocomplete="off" placeholder="Np. Earth-616 albo TRN414"></label><label>Krótki opis<input id="world-description" required autocomplete="off" placeholder="Np. MCU, główne komiksy Marvela, X-Men Foxa"></label><button class="primary-button full" value="save" type="submit">Dodaj świat</button></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>{worldDialogTarget=null;editingWorldId=null;dialog.close()};dialog.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const designation=$('#world-designation').value.trim(),description=$('#world-description').value.trim(),duplicate=projectWorlds().some(world=>world.id!==editingWorldId&&metadataKey(worldLabel(world))===metadataKey(designation));if(!designation||!description||duplicate)return;let world=projectWorlds().find(item=>item.id===editingWorldId);if(world){Object.assign(world,{designation,name:designation,description,draft:false})}else{world={id:uid('world'),designation,name:designation,description};projectWorlds().push(world)}const target=worldDialogTarget;worldDialogTarget=null;editingWorldId=null;save();dialog.close();render();if(target==='event'){if(!selectedEventWorldLabels.includes(designation))selectedEventWorldLabels.push(designation);populateEventWorlds()}if(target==='character')$('#character-world').value=designation;if(target==='source'){ensureSourceWorldFields([world.id]);const input=$(`#source-worlds input[value="${world.id}"]`);if(input)input.checked=true}})}
function openWorldDialog(target=null,worldId=null){if(!activeProject())return openDialog('#project-dialog');worldDialogTarget=target;editingWorldId=worldId;ensureWorldDialog();$('#world-form').reset();const item=projectWorlds().find(world=>world.id===worldId);if(item){$('#world-designation').value=worldLabel(item);$('#world-description').value=item.description||'';$('#world-dialog h2').textContent='Uzupełnij świat';$('#world-form .primary-button').textContent='Zapisz zmiany'}else{$('#world-dialog h2').textContent='Dodaj świat do projektu';$('#world-form .primary-button').textContent='Dodaj świat'}openDialog('#world-dialog')}
function ensureWorldFields(){ensureDateFields();let list=$('#project-world-list');if(!list){list=document.createElement('datalist');list.id='project-world-list';document.body.append(list)}list.innerHTML=projectWorlds().map(world=>`<option value="${escapeHtml(worldLabel(world))}">${escapeHtml(world.description||'')}</option>`).join('');populateEventWorlds();populateEventCharacters()}
function populateEventWorlds(){const search=$('#event-world-search');if(!search)return;const query=metadataKey(search.value),worlds=projectWorlds().filter(world=>!query||metadataKey([worldLabel(world),world.description].join(' ')).includes(query)),selected=$('#event-world-selected'),results=$('#event-world-results');selected.innerHTML=selectedEventWorldLabels.length?selectedEventWorldLabels.map((label,index)=>`<button type="button" data-remove-event-world="${escapeHtml(label)}"><b>${index?'Świat uczestniczący':'Świat główny'}</b>${escapeHtml(label)} <span>×</span></button>`).join(''):'<small>Nie wybrano świata.</small>';results.innerHTML=worlds.filter(world=>!selectedEventWorldLabels.includes(worldLabel(world))).slice(0,40).map(world=>`<button type="button" data-pick-event-world="${escapeHtml(worldLabel(world))}"><b>${escapeHtml(worldLabel(world))}</b><small>${escapeHtml(world.description||'Bez opisu')}</small></button>`).join('')||'<small>Brak pasujących światów.</small>';selected.querySelectorAll('[data-remove-event-world]').forEach(button=>button.onclick=()=>{selectedEventWorldLabels=selectedEventWorldLabels.filter(label=>label!==button.dataset.removeEventWorld);populateEventWorlds()});results.querySelectorAll('[data-pick-event-world]').forEach(button=>button.onclick=()=>{selectedEventWorldLabels.push(button.dataset.pickEventWorld);search.value='';populateEventWorlds()});$('#add-event-world').onclick=()=>openWorldDialog('event')}
function populateEventCharacters(){const search=$('#event-character-search');if(!search)return;const query=metadataKey(search.value),characters=projectCharacters().filter(character=>!query||metadataKey([character.name,...characterAliases(character),character.world].join(' ')).includes(query)),selected=$('#event-character-selected'),results=$('#event-character-results');selected.innerHTML=selectedEventCharacterIds.length?selectedEventCharacterIds.map(id=>{const character=projectCharacters().find(item=>item.id===id);return character?`<button type="button" data-remove-event-character="${id}"><b>Postać</b>${escapeHtml(character.name)} <span>×</span></button>`:''}).join(''):'<small>Nie wybrano postaci.</small>';results.innerHTML=characters.filter(character=>!selectedEventCharacterIds.includes(character.id)).slice(0,40).map(character=>`<button type="button" data-pick-event-character="${character.id}"><b>${escapeHtml(character.name)}</b><small>${escapeHtml([...characterAliases(character),character.world].filter(Boolean).join(' · ')||'Bez dodatkowych nazw')}</small></button>`).join('')||'<small>Brak pasujących postaci.</small>';selected.querySelectorAll('[data-remove-event-character]').forEach(button=>button.onclick=()=>{selectedEventCharacterIds=selectedEventCharacterIds.filter(id=>id!==button.dataset.removeEventCharacter);populateEventCharacters()});results.querySelectorAll('[data-pick-event-character]').forEach(button=>button.onclick=()=>{selectedEventCharacterIds.push(button.dataset.pickEventCharacter);search.value='';populateEventCharacters()});$('#add-event-character').onclick=()=>openCharacterDialog(null,'event')}
function ensureDateFields(){if(!$('#source-date-row')){const row=document.createElement('div');row.id='source-date-row';row.className='form-row';row.innerHTML='<label>Data akcji źródła<input id="source-date" type="text" autocomplete="off" placeholder="Np. 1260 BC, 10 AD, 2026-09-28"></label><label class="check date-check"><input id="source-date-approx" type="checkbox"> Data przybliżona</label>';$('#source-status').closest('.form-row').after(row);const releaseRow=document.createElement('div');releaseRow.id='source-release-row';releaseRow.className='form-row';releaseRow.innerHTML='<label>Data premiery / wydania<input id="source-release-date" type="date" autocomplete="off"></label><label><span>Porządek publikacji</span><small>Osobna od daty akcji. Posłuży do widoku kolejności premier.</small></label>';row.after(releaseRow)}}
function ensureSourceWorldFields(selectedIds=[]){let field=$('#source-worlds'),selected=new Set(selectedIds);if(field)field.querySelectorAll('input:checked').forEach(input=>selected.add(input.value));if(!field){field=document.createElement('fieldset');field.id='source-worlds';field.className='world-links';$('#source-release-row').after(field)}field.innerHTML='<legend>Światy źródła <button id="add-source-world" class="mini-button" type="button" title="Dodaj nowy świat">＋</button></legend><p>Opcjonalnie przypisz jeden lub kilka światów występujących w tym źródle.</p><div>'+projectWorlds().map(world=>`<label><input type="checkbox" value="${world.id}"> ${escapeHtml(worldLabel(world))} · ${escapeHtml(world.description||'')}</label>`).join('')+'</div>';field.querySelectorAll('input').forEach(input=>input.checked=selected.has(input.value));$('#add-source-world').onclick=()=>openWorldDialog('source')}
function ensureSourceRelationFields(){if($('#source-relation-fields'))return;const field=document.createElement('fieldset');field.id='source-relation-fields';field.className='event-picker source-relation-fields';field.innerHTML='<legend>Powiązanie z filmem lub serialem</legend><p>Używaj dla adaptacji, prequeli i komiksów bezpośrednio związanych z ekranowym źródłem.</p><div class="form-row"><label>Rodzaj powiązania<select id="source-relation-type"><option value="">Brak</option><option value="adaptation">Adaptacja</option><option value="prequel">Prequel</option><option value="tiein">Tie-in</option><option value="promotional">Materiał promocyjny</option><option value="associated">Nieoficjalnie łączony</option></select></label><label>Status kanoniczności<select id="source-canon-status"><option value="">Nieustalony</option><option value="kanoniczny">Kanoniczny</option><option value="oficjalny — kanon niejasny">Oficjalny — kanon niejasny</option><option value="niekanoniczny">Niekanoniczny</option><option value="nieoficjalny">Nieoficjalny</option></select></label></div><label>Znajdź film lub serial<input id="source-relation-search" type="search" autocomplete="off" placeholder="Zacznij wpisywać tytuł…"></label><div id="source-relation-selected" class="picker-selected"></div><div id="source-relation-results" class="picker-results"></div>';$('#source-worlds').after(field);$('#source-relation-search').addEventListener('input',populateSourceRelations)}
function populateSourceRelations(){const project=activeProject(),query=metadataKey($('#source-relation-search')?.value),selected=$('#source-relation-selected'),results=$('#source-relation-results');if(!project||!selected||!results)return;selected.innerHTML=selectedRelatedSourceIds.length?selectedRelatedSourceIds.map(id=>{const source=project.sources.find(item=>item.id===id);return source?`<button type="button" data-remove-source-relation="${id}"><b>Powiązane źródło</b>${escapeHtml(source.title)} <span>×</span></button>`:''}).join(''):'<small>Nie wybrano powiązanego filmu lub serialu.</small>';const matches=(project.sources||[]).filter(source=>source.id!==editingSourceId&&!selectedRelatedSourceIds.includes(source.id)&&['Film','Serial','Inne'].includes(source.type)&&query&&metadataKey([source.title,...sourceTags(source),...sourceWorldLabels(source)].join(' ')).includes(query)).slice(0,30);results.innerHTML=query?matches.map(source=>`<button type="button" data-pick-source-relation="${source.id}"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)} · ${escapeHtml(sourceWorldLabels(source).join(' / ')||'świat nieustalony')}</small></button>`).join('')||'<small>Nie znaleziono filmu ani serialu.</small>':'<small>Wpisz fragment tytułu.</small>';selected.querySelectorAll('[data-remove-source-relation]').forEach(button=>button.onclick=()=>{selectedRelatedSourceIds=selectedRelatedSourceIds.filter(id=>id!==button.dataset.removeSourceRelation);populateSourceRelations()});results.querySelectorAll('[data-pick-source-relation]').forEach(button=>button.onclick=()=>{selectedRelatedSourceIds.push(button.dataset.pickSourceRelation);$('#source-relation-search').value='';populateSourceRelations()})}
function openSourceDialog(sourceId=null,target=null){if(!activeProject())return openDialog('#project-dialog');editingSourceId=sourceId;sourceDialogTarget=target;selectedRelatedSourceIds=[];ensureDateFields();$('#source-form').reset();let selected=[];ensureSourceWorldFields(selected);ensureSourceRelationFields();if(sourceId){const item=activeProject().sources.find(source=>source.id===sourceId);if(item){selected=item.worldIds||[];selectedRelatedSourceIds=[...(item.relatedSourceIds||[])];$('#source-title').value=item.title;$('#source-type').value=item.type;$('#source-status').value=item.status;$('#source-date').value=item.date||'';$('#source-date-approx').checked=Boolean(item.dateApprox);$('#source-release-date').value=item.releaseDate||'';$('#source-relation-type').value=item.relationType||'';$('#source-canon-status').value=item.canonStatus||'';$('#source-dialog h2').textContent='Edytuj źródło';$('#source-form .primary-button').textContent='Zapisz zmiany'}}else{$('#source-dialog h2').textContent='Dodaj materiał';$('#source-form .primary-button').textContent='Dodaj do Road'}ensureSourceWorldFields(selected);populateSourceRelations();openDialog('#source-dialog')}
function ensureQuickEventDialog(){if($('#quick-event-dialog'))return;const dialog=document.createElement('dialog');dialog.id='quick-event-dialog';dialog.className='dialog quick-event-dialog';dialog.innerHTML='<form id="quick-event-form"><button class="dialog-close" type="button" aria-label="Zamknij">×</button><p class="eyebrow">NOTATNIK OGLĄDANIA</p><h2>Szybkie wydarzenia</h2><p id="quick-source-name" class="quick-source-name"></p><label>Co się wydarzyło?<input id="quick-event-title" required autocomplete="off" placeholder="Krótka notatka"></label><div class="quick-event-grid"><label>Moment<input id="quick-event-moment" autocomplete="off" placeholder="00:42:15 / str. 18"></label><label>Data lub okres<input id="quick-event-date" autocomplete="off" placeholder="Opcjonalnie"></label><label>Świat<input id="quick-event-world" list="project-world-list" autocomplete="off" placeholder="Wpisz, aby wyszukać"></label><label>Bohaterowie<input id="quick-event-characters" list="quick-character-list" autocomplete="off" placeholder="Peter, May, Tony…"></label></div><label>Luźna notatka<input id="quick-event-note" autocomplete="off" placeholder="Opcjonalnie"></label><datalist id="quick-character-list"></datalist><p id="quick-event-feedback" class="quick-event-feedback">Enter zapisuje i przygotowuje następną pustą notatkę.</p><div class="quick-event-actions"><button id="quick-event-advanced" class="secondary-button" type="button">Pełny formularz</button><button class="primary-button" type="submit">Zapisz i następne ↵</button></div></form>';document.body.append(dialog);dialog.querySelector('.dialog-close').onclick=()=>dialog.close();$('#quick-event-advanced').onclick=()=>{const sourceId=quickEventSourceId;dialog.close();openEventDialog(null,sourceId)};$('#quick-event-form').addEventListener('submit',saveQuickEvent)}
function quickCharacterIds(value,world=''){return value.split(',').map(name=>name.trim()).filter(Boolean).map(name=>{let character=projectCharacters().find(item=>metadataKey([item.name,...characterAliases(item)].join(' ')).split(' ').includes(metadataKey(name))||metadataKey(item.name)===metadataKey(name));if(!character){character={id:uid('character'),name,aliases:[],world,birthDate:'',deathDate:'',draft:true};projectCharacters().push(character)}return character.id})}
function quickWorldLabel(value){const designation=value.trim();if(!designation)return'';const existing=projectWorlds().find(world=>metadataKey(worldLabel(world))===metadataKey(designation)||metadataKey(world.description)===metadataKey(designation));if(existing)return worldLabel(existing);projectWorlds().push({id:uid('world'),designation,name:designation,description:'Szkic z szybkiej notatki',draft:true});return designation}
function saveQuickEvent(event){event.preventDefault();const project=activeProject(),title=$('#quick-event-title').value.trim(),source=project?.sources.find(item=>item.id===quickEventSourceId);if(!project||!source||!title)return;const world=quickWorldLabel($('#quick-event-world').value),characterIds=quickCharacterIds($('#quick-event-characters').value,world),sourceMoment=$('#quick-event-moment').value.trim(),date=$('#quick-event-date').value.trim();project.events.push({id:uid('event'),title,sourceId:source.id,sourceIds:[source.id],sourceMoment,sourceMoments:sourceMoment?{[source.id]:sourceMoment}:{},characterIds,timeType:date?'exact':'unknown',date,dateApprox:false,relations:[],relationEventId:null,world,worldLinks:[],place:'',tags:[],notes:$('#quick-event-note').value.trim(),inbox:true,draft:true,createdAt:new Date().toISOString()});save();render();$('#quick-event-title').value='';$('#quick-event-moment').value='';$('#quick-event-characters').value='';$('#quick-event-note').value='';$('#quick-event-feedback').textContent=`Zapisano: ${title}. Możesz pisać następne.`;$('#quick-event-title').focus()}
function openQuickEventDialog(sourceId){if(!activeProject())return openDialog('#project-dialog');const source=activeProject().sources.find(item=>item.id===sourceId);if(!source)return;quickEventSourceId=sourceId;ensureWorldFields();ensureQuickEventDialog();$('#quick-event-form').reset();$('#quick-source-name').textContent=source.title;$('#quick-event-date').value=source.date||'';const sourceWorlds=sourceWorldLabels(source);$('#quick-event-world').value=sourceWorlds.length===1?sourceWorlds[0]:'';$('#quick-character-list').innerHTML=projectCharacters().map(character=>`<option value="${escapeHtml(character.name)}">${escapeHtml(characterAliases(character).join(' / '))}</option>`).join('');$('#quick-event-feedback').textContent='Enter zapisuje i przygotowuje następną pustą notatkę.';openDialog('#quick-event-dialog')}
function ensureEventSourceMomentField(){if($('#event-source-moment-field'))return;const label=document.createElement('label');label.id='event-source-moment-field';label.hidden=true;label.innerHTML='<span>Moment w źródle</span><input id="event-source-moment" type="text" autocomplete="off" placeholder="Np. 00:42:15, strona 18, rozdział 3"><small>Opcjonalny punkt, w którym wydarzenie pojawia się w głównym źródle.</small>';$('#event-source-picker').after(label)}
function updateEventSourceMomentField(){ensureEventSourceMomentField();const field=$('#event-source-moment-field'),source=activeProject()?.sources.find(item=>item.id===selectedEventSourceIds[0]);field.hidden=!source;field.querySelector('span').textContent=source?`Moment w „${source.title}”`:'Moment w źródle'}
function populateEventSources(){const query=metadataKey($('#event-source-search').value),sources=(activeProject()?.sources||[]).filter(source=>!query||metadataKey([source.title,source.type,...sourceTags(source),...sourceWorldLabels(source)].join(' ')).includes(query)),selected=$('#event-source-selected'),results=$('#event-source-results');selected.innerHTML=selectedEventSourceIds.length?selectedEventSourceIds.map((id,index)=>{const source=activeProject()?.sources.find(item=>item.id===id);return source?`<button type="button" data-remove-event-source="${id}"><b>${index?'Źródło dodatkowe':'Źródło główne'}</b>${escapeHtml(source.title)} <span>×</span></button>`:''}).join(''):'<small>Nie wybrano źródła — możesz zapisać wydarzenie bez niego.</small>';results.innerHTML=sources.filter(source=>!selectedEventSourceIds.includes(source.id)).slice(0,40).map(source=>`<button type="button" data-pick-event-source="${source.id}"><b>${escapeHtml(source.title)}</b><small>${escapeHtml(source.type)} · ${escapeHtml(sourceWorldLabels(source).join(' / ')||'świat nieustalony')}</small></button>`).join('')||'<small>Brak pasujących źródeł.</small>';selected.querySelectorAll('[data-remove-event-source]').forEach(button=>button.onclick=()=>{selectedEventSourceIds=selectedEventSourceIds.filter(id=>id!==button.dataset.removeEventSource);populateEventSources()});results.querySelectorAll('[data-pick-event-source]').forEach(button=>button.onclick=()=>{selectedEventSourceIds.push(button.dataset.pickEventSource);$('#event-source-search').value='';populateEventSources()});$('#add-event-source').onclick=()=>openSourceDialog(null,'event');updateEventSourceMomentField()}
function ensureRelationPicker(){if($('#event-relation-search').dataset.bound)return;$('#event-relation-search').dataset.bound='true';$('#event-relation-search').addEventListener('input',renderRelationPicker);$('#event-relation-type').addEventListener('change',renderRelationPicker)}
function relationHaystack(event){const names=projectCharacters().filter(character=>(event.characterIds||[]).includes(character.id)).flatMap(character=>[character.name,...characterAliases(character)]);return [event.title,event.world,event.place,event.notes,...eventSources(event).map(source=>source.title),...names,...(event.tags||[])].filter(Boolean).join(' ').toLowerCase()}
function renderRelationPicker(){const project=activeProject(),query=metadataKey($('#event-relation-search').value),type=$('#event-relation-type').value,selected=$('#event-relation-selected'),results=$('#event-relation-results');selected.innerHTML=selectedEventRelations.length?selectedEventRelations.map((relation,index)=>{const item=project?.events.find(event=>event.id===relation.eventId);return item?`<button type="button" data-remove-event-relation="${index}"><b>${timeLabel(relation.type)}</b>${escapeHtml(item.title)} <span>×</span></button>`:''}).join(''):'<small>Relacje są opcjonalne; możesz dodać ich kilka.</small>';const events=(project?.events||[]).filter(event=>event.id!==editingEventId&&!selectedEventRelations.some(relation=>relation.type===type&&relation.eventId===event.id)&&(!query||metadataKey(relationHaystack(event)).includes(query))).slice(0,40);results.innerHTML=query?events.map(event=>`<button class="relation-option" type="button" data-event-id="${event.id}"><b>${escapeHtml(event.title)}</b><small>${escapeHtml([event.world,event.place,...eventSources(event).map(source=>source.title)].filter(Boolean).join(' · ')||'Bez dodatkowych danych')}</small></button>`).join('')||'<small>Nie znaleziono pasującego wydarzenia.</small>':'<small>Zacznij pisać, aby znaleźć wydarzenie odniesienia.</small>';selected.querySelectorAll('[data-remove-event-relation]').forEach(button=>button.onclick=()=>{selectedEventRelations.splice(Number(button.dataset.removeEventRelation),1);renderRelationPicker()});results.querySelectorAll('[data-event-id]').forEach(button=>button.onclick=()=>{selectedEventRelations.push({type,eventId:button.dataset.eventId});$('#event-relation-search').value='';renderRelationPicker()})}
function openEventDialog(eventId=null,presetSourceId=null){if(!activeProject())return openDialog('#project-dialog');editingEventId=eventId;$('#event-form').reset();$('#event-inbox').checked=true;selectedEventRelations=[];selectedEventSourceIds=presetSourceId?[presetSourceId]:[];selectedEventCharacterIds=[];selectedEventWorldLabels=[];ensureWorldFields();ensureRelationPicker();if(eventId){const item=activeProject().events.find(event=>event.id===eventId);if(item){selectedEventSourceIds=eventSourceIds(item);selectedEventRelations=eventRelations(item);selectedEventCharacterIds=[...(item.characterIds||[])];selectedEventWorldLabels=[item.world,...(item.worldLinks||[])].filter(Boolean);$('#event-title').value=item.title;$('#event-date').value=item.date||'';$('#event-date-approx').checked=Boolean(item.dateApprox??item.timeType==='approx');$('#event-source-moment').value=item.sourceMoment||item.sourceMoments?.[selectedEventSourceIds[0]]||'';$('#event-place').value=item.place||'';$('#event-tags').value=(item.tags||[]).join(', ');$('#event-notes').value=item.notes||'';$('#event-inbox').checked=Boolean(item.inbox);$('#event-dialog h2').textContent='Edytuj wydarzenie';$('#event-form .primary-button').textContent='Zapisz zmiany'}}else{$('#event-dialog h2').textContent=presetSourceId?'Dodaj wydarzenie ze źródła':'Dodaj wydarzenie';$('#event-form .primary-button').textContent='Zapisz i dodaj następne'}populateEventSources();populateEventCharacters();populateEventWorlds();renderRelationPicker();openDialog('#event-dialog')}
function saveEvent(event){event.preventDefault();const project=activeProject(),title=$('#event-title').value.trim();if(!project||!title)return;const sourceId=selectedEventSourceIds[0]||null,sourceMoment=$('#event-source-moment').value.trim(),date=$('#event-date').value.trim(),relations=selectedEventRelations.map(relation=>({...relation})),legacyRelation=relations[0]||null,data={title,sourceId,sourceIds:[...selectedEventSourceIds],sourceMoment,sourceMoments:sourceId&&sourceMoment?{[sourceId]:sourceMoment}:{},characterIds:[...selectedEventCharacterIds],timeType:date?($('#event-date-approx').checked?'approx':'exact'):(legacyRelation?.type||'unknown'),date,dateApprox:$('#event-date-approx').checked,relations,relationEventId:legacyRelation?.eventId||null,world:selectedEventWorldLabels[0]||'',worldLinks:selectedEventWorldLabels.slice(1),place:$('#event-place').value.trim(),tags:$('#event-tags').value.split(',').map(tag=>tag.trim()).filter(Boolean),notes:$('#event-notes').value.trim(),inbox:$('#event-inbox').checked};if(editingEventId){const item=project.events.find(existing=>existing.id===editingEventId);if(item)Object.assign(item,data);editingEventId=null;save();$('#event-dialog').close();render();return}project.events.push({id:uid('event'),...data,createdAt:new Date().toISOString()});save();event.currentTarget.reset();selectedEventRelations=[];selectedEventCharacterIds=[];selectedEventWorldLabels=[];selectedEventSourceIds=sourceId?[sourceId]:[];$('#event-source-moment').value='';$('#event-inbox').checked=true;populateEventSources();populateEventCharacters();populateEventWorlds();renderRelationPicker();render();$('#event-title').focus()}

ensureEventSourceMomentField();
$$('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$$('[data-view-search]').forEach(input=>input.addEventListener('input',()=>{const view=input.dataset.viewSearch;viewSearch[view]=input.value;if(view==='sources')sourcePage=0;({road:renderRoad,sources:renderSources,worlds:renderWorlds,characters:renderCharacters,events:renderEvents})[view]?.()}));
$$('.dialog-close').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close()}));
$('#brand-home').addEventListener('click',()=>switchView('road'));
$('#theme-button').addEventListener('click',openThemeDialog);
$('#new-project-main').addEventListener('click',()=>activeProject()?openSourceDialog():openDialog('#project-dialog'));
$('#new-project-side').addEventListener('click',()=>openDialog('#project-dialog'));
$('#quick-event-button').addEventListener('click',()=>openEventDialog());$('#add-event-button').addEventListener('click',()=>openEventDialog());$('#add-source-button').addEventListener('click',()=>openSourceDialog());$('#add-character-button').addEventListener('click',()=>openCharacterDialog());
$('#event-form').addEventListener('submit',saveEvent);document.body.dataset.eventSubmitReady='true';
$('#add-world-view-button').addEventListener('click',()=>openWorldDialog());
$('#event-source-search').addEventListener('input',populateEventSources);
$('#event-character-search').addEventListener('input',populateEventCharacters);
$('#event-world-search').addEventListener('input',populateEventWorlds);
$('#project-select').addEventListener('change',event=>{state.activeProjectId=event.target.value||null;save();render()});
$('.main').addEventListener('click',event=>{const button=event.target.closest('button[data-id]');if(!button)return;const project=activeProject(),id=button.dataset.id;if(button.classList.contains('add-event-from-source'))openQuickEventDialog(id);if(button.classList.contains('edit-source'))openSourceDialog(id);if(button.classList.contains('edit-event'))openEventDialog(id);if(button.classList.contains('edit-character'))openCharacterDialog(id);if(button.classList.contains('edit-world'))openWorldDialog(null,id);if(button.classList.contains('delete-source')&&confirm('Usunąć to źródło? Powiązane wydarzenia pozostaną w projekcie.')){project.sources=project.sources.filter(source=>source.id!==id);project.events.forEach(item=>{if(item.sourceId===id)item.sourceId=null;item.sourceIds=eventSourceIds(item).filter(sourceId=>sourceId!==id)});save();render()}if(button.classList.contains('delete-event')&&confirm('Usunąć to wydarzenie?')){project.events=project.events.filter(item=>item.id!==id);project.events.forEach(item=>{if(item.relationEventId===id)item.relationEventId=null;if(Array.isArray(item.relations))item.relations=item.relations.filter(relation=>relation.eventId!==id)});save();render()}if(button.classList.contains('delete-character')&&confirm('Usunąć tę postać? Zniknie także z przypisanych wydarzeń.')){project.characters=projectCharacters().filter(character=>character.id!==id);project.events.forEach(item=>item.characterIds=(item.characterIds||[]).filter(characterId=>characterId!==id));save();render()}if(button.classList.contains('delete-world')&&confirm('Usunąć ten świat z kartoteki?')){project.worlds=projectWorlds().filter(world=>world.id!==id);save();render()}});
$('#project-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const name=$('#project-name').value.trim();if(!name)return;const project={id:uid('project'),name,description:$('#project-description').value.trim(),createdAt:new Date().toISOString(),worlds:[],sources:[],characters:[],events:[]};state.projects.push(project);state.activeProjectId=project.id;save();event.currentTarget.reset();$('#project-dialog').close();render();switchView('road')});
$('#source-form').addEventListener('submit',event=>{if(event.submitter?.value!=='save')return;event.preventDefault();const project=activeProject(),title=$('#source-title').value.trim();if(!project||!title)return;const data={title,type:$('#source-type').value,status:$('#source-status').value,date:$('#source-date')?.value||'',dateApprox:$('#source-date-approx')?.checked||false,releaseDate:$('#source-release-date')?.value||'',worldIds:[...$('#source-worlds').querySelectorAll('input:checked')].map(input=>input.value),relatedSourceIds:[...selectedRelatedSourceIds],relationType:$('#source-relation-type')?.value||'',canonStatus:$('#source-canon-status')?.value||''};let sourceId=editingSourceId;if(editingSourceId){const item=project.sources.find(source=>source.id===editingSourceId);if(item)Object.assign(item,data)}else{sourceId=uid('source');project.sources.push({id:sourceId,...data,createdAt:new Date().toISOString()})}const target=sourceDialogTarget;editingSourceId=null;sourceDialogTarget=null;selectedRelatedSourceIds=[];save();event.currentTarget.reset();$('#source-dialog').close();render();if(target==='event'){if(!selectedEventSourceIds.includes(sourceId))selectedEventSourceIds.push(sourceId);populateEventSources()}else switchView('road')});

$('.main').addEventListener('click',event=>{const button=event.target.closest('[data-character-focus]');if(!button)return;selectedCharacterId=button.dataset.characterFocus;roadMode='events';renderRoad();switchView('road')});
migrateLegacySourceTags();applyTheme();render();switchView('road');void runCatalogMigrations();
